import { ProspectiveLab, sha256, stableJson, type EventEnvelope } from "./prospective_ab_lab.js";

export type PricePoint={at:string;slot:number|null;price:number|null;label:"SOURCE_FILL"|"SLOT_1"|"SLOT_2"|"SLOT_3"|"SEC_5"|"SEC_10"|"FOLLOWER_FILL"};
export type Flight={schemaVersion:1;flightId:string;sourceWallet:string;sourceSignature:string;sourceSlot:number|null;sourceBlockTime:number|null;firstProviderSeenAt:string;providerSeenAt:Record<string,string>;scoutReceivedAt:string;scoutClassifiedAt:string|null;eligibilityDecidedAt:string|null;eligible:boolean|null;odinExpectedAction:string|null;odinObservedAction:string|null;followerSignature:string|null;followerSlot:number|null;followerBlockTime:number|null;sourcePrice:number|null;expectedFollowerPrice:number|null;actualFollowerPrice:number|null;providerDeliveryLagMs:number|null;scoutDecisionLagMs:number|null;odinLagMs:number|null;landingSlotLag:number|null;slippageBps:number|null;totalCopyLagMs:number|null;manifestHash:string;};

const ms=(a:string|null,b:string|null)=>a&&b?Date.parse(b)-Date.parse(a):null;
export class FlightRecorder{
 private flights=new Map<string,Flight>(); constructor(private lab:ProspectiveLab,private manifestHash:string){}
 source(e:EventEnvelope):Flight|null{if(!e.signature||e.role==="FOLLOWER")return null; const k=e.signature; let f=this.flights.get(k); if(!f){f={schemaVersion:1,flightId:sha256(`${e.wallet}:${k}`),sourceWallet:e.wallet??"UNKNOWN",sourceSignature:k,sourceSlot:e.slot,sourceBlockTime:e.blockTime,firstProviderSeenAt:e.receivedAt,providerSeenAt:{[e.transport]:e.receivedAt},scoutReceivedAt:e.receivedAt,scoutClassifiedAt:null,eligibilityDecidedAt:null,eligible:null,odinExpectedAction:null,odinObservedAction:null,followerSignature:null,followerSlot:null,followerBlockTime:null,sourcePrice:null,expectedFollowerPrice:null,actualFollowerPrice:null,providerDeliveryLagMs:e.providerCreatedAt?ms(e.providerCreatedAt,e.receivedAt):null,scoutDecisionLagMs:null,odinLagMs:null,landingSlotLag:null,slippageBps:null,totalCopyLagMs:null,manifestHash:this.manifestHash};this.flights.set(k,f);}else f.providerSeenAt[e.transport]=e.receivedAt; this.lab.commitFlight({kind:"SOURCE_SEEN",at:new Date().toISOString(),flight:f});return f;}
 decision(sourceSignature:string,args:{classifiedAt:string;decidedAt:string;eligible:boolean;odinExpectedAction:string|null}){const f=this.flights.get(sourceSignature);if(!f)return;Object.assign(f,{scoutClassifiedAt:args.classifiedAt,eligibilityDecidedAt:args.decidedAt,eligible:args.eligible,odinExpectedAction:args.odinExpectedAction,scoutDecisionLagMs:ms(f.scoutReceivedAt,args.decidedAt)});this.lab.commitFlight({kind:"SCOUT_DECISION",at:args.decidedAt,flight:f});}
 odin(sourceSignature:string,observedAction:string,at:string){const f=this.flights.get(sourceSignature);if(!f)return;f.odinObservedAction=observedAction;f.odinLagMs=ms(f.eligibilityDecidedAt,at);this.lab.commitFlight({kind:"ODIN_OBSERVED",at,flight:f});}
 follower(sourceSignature:string,e:EventEnvelope,actualPrice:number|null){const f=this.flights.get(sourceSignature);if(!f||!e.signature)return;f.followerSignature=e.signature;f.followerSlot=e.slot;f.followerBlockTime=e.blockTime;f.actualFollowerPrice=actualPrice;f.landingSlotLag=f.sourceSlot!=null&&e.slot!=null?e.slot-f.sourceSlot:null;f.totalCopyLagMs=f.sourceBlockTime!=null&&e.blockTime!=null?(e.blockTime-f.sourceBlockTime)*1000:null;f.slippageBps=f.sourcePrice&&actualPrice?((actualPrice/f.sourcePrice)-1)*10000:null;this.lab.commitFlight({kind:"FOLLOWER_FILL",at:e.receivedAt,flight:f});}
 prices(sourceSignature:string,points:PricePoint[]){const f=this.flights.get(sourceSignature);if(!f)return;const src=points.find(x=>x.label==="SOURCE_FILL")?.price??null,actual=points.find(x=>x.label==="FOLLOWER_FILL")?.price??null;f.sourcePrice=src;f.actualFollowerPrice=actual;this.lab.commitExecutionDecay({schemaVersion:1,flightId:f.flightId,sourceSignature,points,decay:points.map(p=>({label:p.label,returnBps:src&&p.price?((p.price/src)-1)*10000:null})),hash:sha256(stableJson(points)),at:new Date().toISOString()});}
}
