import { promises as fs } from "node:fs";
import path from "node:path";

const CP_PATH=process.env.SCOUT_GAUNTLET_STATE_PATH||"./data/gauntlet-state.json";
const STATE_PATH=process.env.SCOUT_STATE_PATH||"./data/shark-state.json";
const OUT_PATH=process.env.SCOUT_CANONICAL_GAUNTLET_PATH||"./data/canonical-gauntlet.json";
const TOP=Math.max(10,Math.min(100,Number(process.env.CANONICAL_GAUNTLET_TOP||40)));

type AnyObj=Record<string,any>;
function now(){return new Date().toISOString();}
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:null;}
function sum(xs:number[]){return xs.reduce((a,b)=>a+b,0);}
async function read(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomic(file:string,data:any){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(data));await fs.rename(tmp,file);}
function capped(trips:any[],dailyCap=2){const groups=new Map<string,any[]>();for(const r of trips){const k=`${r.mint}|${r.buyTimestamp}`,a=groups.get(k)||[];a.push(r);groups.set(k,a);}const entries=[...groups.values()].sort((a,b)=>Number(a[0]?.buyTimestamp)-Number(b[0]?.buyTimestamp)),daily=new Map<string,number>();let selected=0,net=0,s50=0,s75=0,wins=0;for(const g of entries){const f=g[0],day=new Date(Number(f?.buyTimestamp||0)*1000).toISOString().slice(0,10);if((daily.get(day)||0)>=dailyCap)continue;const ns=g.map(x=>n(x?.followerNetSol)).filter((x):x is number=>x!=null);if(!ns.length)continue;const x=sum(ns);net+=x;s50+=sum(g.map(x=>n(x?.stress50NetSol)).filter((x):x is number=>x!=null));s75+=sum(g.map(x=>n(x?.stress75NetSol)).filter((x):x is number=>x!=null));if(x>0)wins++;selected++;daily.set(day,(daily.get(day)||0)+1);}return{dailyCap,selected,netSol:net,stress50NetSol:s50,stress75NetSol:s75,winRate:selected?wins/selected:null};}
function quality(r:any,w:any){const closed=Number(r?.hold?.closedHolds||0),buys=Number(r?.hold?.buyEvents||0),partial=Boolean(r?.heliusCoveragePartial),disc=Number(r?.discoveryTokens||w?.tokens?.length||0),coverage=buys>0?Math.min(1,closed/buys):null;let risk=0;const reasons:string[]=[];if(partial){risk=2;reasons.push("helius_history_partial");}if(closed<10){risk=2;reasons.push("closed_sample_lt_10");}else if(closed<20){risk=Math.max(risk,1);reasons.push("closed_sample_lt_20");}if(disc<2){risk=Math.max(risk,1);reasons.push("single_discovery_context");}if(coverage!=null&&coverage<.35){risk=2;reasons.push("low_close_to_buy_coverage");}return{risk:risk>=2?"HIGH":risk===1?"MEDIUM":"LOW",reasons,closed,buys,coverage,discoveryContexts:disc};}
function verdict(r:any,w:any){const med=n(r?.hold?.medianHoldSeconds),cr=r?.canonicalReplay,tr=Array.isArray(cr?.roundTrips)?cr.roundTrips:[],t=cr?.trusted||{},q=quality(r,w),rp=capped(tr,2),largest=n(t?.largestWinnerShare),reasons:string[]=[];if(med==null)return{status:"UNKNOWN",stage:"hold_unknown",reasons:["median_hold_unknown"],rp,q};if(med<600)return{status:"REJECT",stage:"hold_time",reasons:["median_hold_under_10m"],rp,q};if(med<3600)return{status:"SIGNAL_ONLY",stage:"hold_time",reasons:["median_hold_10m_to_1h"],rp,q};const trades=Number(t?.trades||0),net=n(t?.netSol),s50=n(t?.stress50NetSol);if(trades>=10&&net!=null&&net<=0)return{status:"REJECT",stage:"canonical_economics",reasons:["canonical_net_nonpositive"],rp,q};if(largest!=null&&largest>.60&&trades>=10)return{status:"REJECT",stage:"canonical_robustness",reasons:["largest_winner_over_60pct"],rp,q};const common=trades>=10&&net!=null&&net>0&&s50!=null&&s50>0&&rp.selected>=5&&rp.netSol>0&&rp.stress50NetSol>0&&largest!=null&&largest<=.60&&q.risk!=="HIGH";if(med>=21600&&common&&q.closed>=10&&q.discoveryContexts>=2)return{status:"DEEP_DIVE",stage:"canonical_odin_replay",reasons:["median_hold_6h_plus","canonical_trades_10_plus","two_per_day_positive","stress50_positive","anti_jackpot","multi_context"],rp,q};const prospect=trades>=15&&net!=null&&net>0&&s50!=null&&s50>0&&rp.selected>=5&&rp.netSol>0&&rp.stress50NetSol>0&&rp.stress75NetSol>0&&largest!=null&&largest<=.45&&q.risk!=="HIGH"&&q.closed>=10&&q.discoveryContexts>=2;if(med>=3600&&med<21600&&prospect)return{status:"ODIN_PROSPECT",stage:"canonical_odin_replay",reasons:["median_hold_1h_to_6h","canonical_trades_15_plus","two_per_day_positive","stress75_positive","largest_winner_share_lte_45pct","multi_context"],rp,q};reasons.push(trades<10?"canonical_trades_lt_10":"canonical_sample_present");if(net==null)reasons.push("canonical_net_unknown");else if(net>0)reasons.push("canonical_net_positive");if(s50==null)reasons.push("stress50_unknown");else if(s50>0)reasons.push("stress50_positive");if(q.discoveryContexts<2)reasons.push("single_discovery_context");if(q.risk==="HIGH")reasons.push(...q.reasons.map(x=>`sample:${x}`));return{status:"SIGNAL_ONLY",stage:"needs_more_canonical_evidence",reasons,rp,q};}
function priority(row:any){const status=String(row?.canonicalVerdict?.status||"");const base=status==="DEEP_DIVE"?10000:status==="ODIN_PROSPECT"?8000:status==="SIGNAL_ONLY"?1000:0,t=Number(row?.trusted?.trades||0),n0=Number(row?.trusted?.netSol||0),contexts=Number(row?.sampleQuality?.discoveryContexts||0);return base+Math.min(2500,t*75)+Math.min(2500,Math.max(0,n0)*500)+contexts*300;}
export async function runCanonicalGauntletOverlay(){const startedAt=now(),[cp,state]=await Promise.all([read(CP_PATH,{results:{}}),read(STATE_PATH,{wallets:{}})]),rows:any[]=[];const counts:AnyObj={};for(const[address,r0]of Object.entries(cp?.results||{})){const r=r0 as AnyObj,w=state?.wallets?.[address]||{},v=verdict(r,w),cr=r?.canonicalReplay||{};if(!cr?.trusted)continue;const row={address,legacyStatus:r?.verdict?.status||null,canonicalVerdict:{status:v.status,stage:v.stage,reasons:v.reasons},medianHoldHours:n(r?.hold?.medianHoldSeconds)!=null?Number(r.hold.medianHoldSeconds)/3600:null,trusted:cr.trusted,canonicalHistoryRows:cr.historyRows??null,canonicalHistoryComplete:Boolean(cr.historyComplete),sampleQuality:v.q,capped2PerDay:v.rp,providers:w?.providers||[],lanes:w?.lanes||[],discoveryScore:w?.discovery?.outcomeMiner?.score??null};rows.push(row);counts[v.status]=(counts[v.status]||0)+1;if(r?.canonicalOverlay?.status!==v.status||r?.canonicalOverlay?.stage!==v.stage)r.canonicalOverlay={version:"odin_overlay_v2",updatedAt:now(),status:v.status,stage:v.stage,reasons:v.reasons,capped2PerDay:v.rp,sampleQuality:v.q};}
rows.sort((a,b)=>priority(b)-priority(a));cp.updatedAt=now();await atomic(CP_PATH,cp);const out={schemaVersion:2,event:"shark_scout_canonical_gauntlet_complete",startedAt,finishedAt:now(),evaluated:rows.length,counts,deepDive:rows.filter(x=>x.canonicalVerdict.status==="DEEP_DIVE").slice(0,TOP),odinProspects:rows.filter(x=>x.canonicalVerdict.status==="ODIN_PROSPECT").slice(0,TOP),topSignals:rows.filter(x=>x.canonicalVerdict.status==="SIGNAL_ONLY").slice(0,TOP),notes:["Canonical overlay never auto-promotes or modifies Odin settings.","Sub-10m remains hard reject; 10m-1h remains signal-only.","DEEP_DIVE keeps >=6h behavior and requires >=10 canonical trades plus 2/day stress survival.","ODIN_PROSPECT admits 1-6h only with stricter >=15 canonical trades, stress75 survival, <=45% largest-winner share, and independent multi-context discovery."]};await atomic(OUT_PATH,out);console.log(JSON.stringify(out));return out;}
if(import.meta.url===`file://${process.argv[1]}`)runCanonicalGauntletOverlay().catch(e=>{console.error(JSON.stringify({event:"shark_scout_canonical_gauntlet_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});
