import { promises as fs } from "node:fs";
import path from "node:path";
import { canonicalMedianHoldSeconds, evaluatePromotion, PROMOTION_CONTRACT_VERSION } from "./promotion_contract.js";
const CP_PATH=process.env.SCOUT_GAUNTLET_STATE_PATH||"./data/gauntlet-state.json";
const STATE_PATH=process.env.SCOUT_STATE_PATH||"./data/shark-state.json";
const OUT_PATH=process.env.SCOUT_CANONICAL_GAUNTLET_PATH||"./data/canonical-gauntlet.json";
const TOP=Math.max(10,Math.min(100,Number(process.env.CANONICAL_GAUNTLET_TOP||40)));
type AnyObj=Record<string,any>;
function now(){return new Date().toISOString();}
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:null;}
async function read(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomic(file:string,data:any){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(data));await fs.rename(tmp,file);}
function priority(row:any){const status=String(row?.canonicalVerdict?.status||"");const base=status==="DEEP_DIVE"?10000:status==="ODIN_PROSPECT"?8000:status==="SIGNAL_ONLY"?1000:0,t=Number(row?.trusted?.trades||0),n0=Number(row?.trusted?.netSol||0),contexts=Number(row?.sampleQuality?.discoveryContexts||0);return base+Math.min(2500,t*75)+Math.min(2500,Math.max(0,n0)*500)+contexts*300;}
export async function runCanonicalGauntletOverlay(){const startedAt=now(),[cp,state]=await Promise.all([read(CP_PATH,{results:{}}),read(STATE_PATH,{wallets:{}})]),rows:any[]=[];const counts:AnyObj={};for(const[address,r0]of Object.entries(cp?.results||{})){const r=r0 as AnyObj,w=state?.wallets?.[address]||{},v=evaluatePromotion(r,w),cr=r?.canonicalReplay||{};if(!cr?.trusted)continue;const canonicalMed=canonicalMedianHoldSeconds(r),effectiveMed=canonicalMed??n(r?.hold?.medianHoldSeconds);const row={address,legacyStatus:r?.verdict?.status||null,canonicalVerdict:{status:v.status,stage:v.stage,reasons:v.reasons},medianHoldHours:effectiveMed!=null?Number(effectiveMed)/3600:null,canonicalMedianHoldSeconds:canonicalMed,trusted:cr.trusted,canonicalHistoryRows:cr.historyRows??null,canonicalHistoryComplete:Boolean(cr.historyComplete),sampleQuality:v.q,capped2PerDay:v.rp,providers:w?.providers||[],lanes:w?.lanes||[],discoveryScore:w?.discovery?.outcomeMiner?.score??null};rows.push(row);counts[v.status]=(counts[v.status]||0)+1;r.canonicalOverlay={version:PROMOTION_CONTRACT_VERSION,updatedAt:now(),status:v.status,stage:v.stage,reasons:v.reasons,capped2PerDay:v.rp,sampleQuality:v.q,canonicalMedianHoldSeconds:canonicalMed,effectiveMedianHoldSeconds:effectiveMed,canonicalHistoryComplete:Boolean(cr.historyComplete),canonicalHistoryRows:cr.historyRows??null};}rows.sort((a,b)=>priority(b)-priority(a));cp.updatedAt=now();await atomic(CP_PATH,cp);const out={schemaVersion:4,event:"shark_scout_canonical_gauntlet_complete",promotionContractVersion:PROMOTION_CONTRACT_VERSION,startedAt,finishedAt:now(),evaluated:rows.length,counts,deepDive:rows.filter(x=>x.canonicalVerdict.status==="DEEP_DIVE").slice(0,TOP),odinProspects:rows.filter(x=>x.canonicalVerdict.status==="ODIN_PROSPECT").slice(0,TOP),topSignals:rows.filter(x=>x.canonicalVerdict.status==="SIGNAL_ONLY").slice(0,TOP),notes:["Promotion thresholds live in one shared promotion_contract module.","Canonical behavior metadata is persisted with the verdict so downstream layers cannot regress to stale shallow profile fields.","Canonical overlay never changes Odin settings."]};await atomic(OUT_PATH,out);console.log(JSON.stringify(out));return out;}
if(import.meta.url===`file://${process.argv[1]}`)runCanonicalGauntletOverlay().catch(e=>{console.error(JSON.stringify({event:"shark_scout_canonical_gauntlet_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});