import { promises as fs } from "node:fs";
import path from "node:path";
import { researchFocusWallets, walletPolicy } from "./wallet_policy.js";

const PAPER_STATE=process.env.SCOUT_PAPER_ODIN_STATE_PATH||"/data/paper-odin-state.json";
const PAPER_REPORT=process.env.SCOUT_PAPER_ODIN_REPORT_PATH||"/data/paper-odin-report.json";
const CAP_AUDIT=process.env.SCOUT_ODIN_CAP_AUDIT_PATH||"/data/odin-cap-audit.json";
const ACTUAL=process.env.SCOUT_ODIN_ACTUAL_RECONCILIATION_PATH||"/data/odin-actual-reconciliation.json";
const OUT=process.env.SCOUT_CAPITAL_EXPANSION_LAB_PATH||"/data/capital-expansion-lab.json";
const REASONS=new Set(["TOKEN_WEEK_CAP","TOKEN_DAY_CAP","DAILY_CAP"]);
function now(){return new Date().toISOString();}
async function read(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomic(file:string,data:any){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(data,null,2));await fs.rename(tmp,file);}
function focusWallets(){const explicit=(process.env.CAPITAL_EXPANSION_FOCUS||"").split(",").map(x=>x.trim()).filter(Boolean);if(explicit.length)return explicit;return researchFocusWallets().filter(a=>walletPolicy(a).dailyCap>=2);}
function firstSellAfter(ledger:any[],wallet:string,mint:string,ts:number){return ledger.filter(x=>x?.wallet===wallet&&x?.action==="SIGNAL"&&x?.side==="SELL"&&x?.mint===mint&&Number(x?.sourceTimestamp||0)>ts).sort((a,b)=>Number(a.sourceTimestamp)-Number(b.sourceTimestamp))[0]||null;}
function blockedLedger(ledger:any[],wallet:string){const signals=new Map<string,any>();for(const x of ledger)if(x?.wallet===wallet&&x?.action==="SIGNAL")signals.set(String(x.opportunityId||""),x);const out:any[]=[];for(const x of ledger){if(x?.wallet!==wallet||x?.action!=="SKIP_BUY"||!REASONS.has(String(x?.reason||"")))continue;const id=String(x.opportunityId||""),buy=signals.get(id),mint=String(x?.mint||buy?.mint||""),ts=Number(x?.sourceTimestamp||buy?.sourceTimestamp||0),sell=mint&&ts?firstSellAfter(ledger,wallet,mint,ts):null;out.push({opportunityId:id,mint,reason:String(x.reason),sourceBuyAt:ts?new Date(ts*1000).toISOString():null,sourceSellObserved:Boolean(sell),sourceSellAt:sell?.sourceTimestamp?new Date(Number(sell.sourceTimestamp)*1000).toISOString():null,sourceSellSignature:sell?.signature||null});}return out;}
function hypothesis(reason:string,count:number,closed:number,distinctMints:number){const common={blockedOpportunities:count,sourceExitObserved:closed,distinctMints,evidenceRequirement:{minOpportunities:reason==="DAILY_CAP"?8:5,minDistinctMints:reason==="DAILY_CAP"?4:3,requiresFollowerEconomics:true,requiresPositiveBase:true,requiresPositiveStress50:true,maxSingleWinnerShare:.6}};if(reason==="TOKEN_WEEK_CAP")return{setting:"tokenWeekCap",from:1,to:2,priority:3,...common};if(reason==="TOKEN_DAY_CAP")return{setting:"tokenDayCap",from:1,to:2,priority:2,...common};return{setting:"dailyCap",from:null,to:"current+1",priority:1,...common};}
async function main(){const generatedAt=now(),[state,report,cap,actual]=await Promise.all([read(PAPER_STATE,{ledger:[]}),read(PAPER_REPORT,{wallets:[]}),read(CAP_AUDIT,{rows:[]}),read(ACTUAL,{byMirror:[]})]),ledger=Array.isArray(state?.ledger)?state.ledger:[],rows:any[]=[];for(const address of focusWallets()){const policy=walletPolicy(address),paper=(Array.isArray(report?.wallets)?report.wallets:[]).find((x:any)=>x?.address===address)||null,actualRow=(Array.isArray(actual?.byMirror)?actual.byMirror:[]).find((x:any)=>x?.mirror===address)||null,capRow=(Array.isArray(cap?.rows)?cap.rows:[]).find((x:any)=>x?.address===address)||null,blocked=blockedLedger(ledger,address),groups=new Map<string,any[]>();for(const x of blocked){const a=groups.get(x.reason)||[];a.push(x);groups.set(x.reason,a);}const hypotheses=[...groups.entries()].map(([reason,xs])=>hypothesis(reason,xs.length,xs.filter(x=>x.sourceSellObserved).length,new Set(xs.map(x=>x.mint).filter(Boolean)).size)).sort((a,b)=>b.priority-a.priority||b.blockedOpportunities-a.blockedOpportunities);const leader=hypotheses[0]||null;rows.push({address,policy,paper:paper?{paperBuys:paper.paperBuys,openPositions:paper.openPositions,closedPositions:paper.closedPositions,realizedNetSol:paper.realizedNetSol,winRate:paper.winRate,skipReasons:paper.skipReasons}:null,actual:actualRow,capAudit:capRow?.recommendation||null,blockedOpportunities:blocked,hypotheses,priorityHypothesis:leader?{...leader,status:"COLLECT_PROSPECTIVE_FOLLOWER_ECONOMICS"}:null,recommendation:leader?"KEEP_LIVE_SETTINGS_WHILE_COUNTERFACTUAL_ACCRUES":"NO_RESTRICTION_SIGNAL_YET"});}const out={schemaVersion:1,event:"shark_scout_capital_expansion_lab_complete",generatedAt,guardrails:{capitalMutation:false,odinMutation:false,providerCalls:0,forwardEvidenceRequired:true},wallets:rows,notes:["This lab turns live-policy skips into durable counterfactual opportunity identities instead of leaving them as aggregate counts.","A source sell marks lifecycle observability only; it is not treated as follower P&L because skipped entries do not yet contain enough source economics for trustworthy simulation.","Live loosening remains blocked until prospective follower economics are available and pass base/stress-50 breadth requirements."]};await atomic(OUT,out);console.log(JSON.stringify(out));}
main().catch(e=>{console.error(JSON.stringify({event:"shark_scout_capital_expansion_lab_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});
