import { promises as fs } from "node:fs";

const CIELO_API_KEY=process.env.CIELO_API_KEY?.trim();
const REPORT_PATH=process.env.SCOUT_GAUNTLET_PATH||"./data/latest-gauntlet.json";
const CHECKPOINT_PATH=process.env.SCOUT_GAUNTLET_STATE_PATH||"./data/gauntlet-state.json";
const TIMEOUT_MS=Math.max(3000,Math.min(60000,Number(process.env.REQUEST_TIMEOUT_MS||25000)));
const BASE="https://feed-api.cielo.finance/api/v1";

type AnyObj=Record<string,any>;
type GateStatus="PASS"|"SIGNAL_ONLY"|"REJECT"|"UNKNOWN";

function sleep(ms:number){return new Promise(r=>setTimeout(r,ms));}
function num(v:any){if(typeof v==="number"&&Number.isFinite(v))return v;if(typeof v==="string"){const n=Number(v.replace(/[,$%]/g,""));return Number.isFinite(n)?n:null;}return null;}
function parseDuration(v:any):number|null{if(typeof v==="number"&&Number.isFinite(v))return v;if(typeof v!=="string")return null;const s=v.trim().toLowerCase();const direct=Number(s);if(Number.isFinite(direct))return direct;let total=0,hit=false;for(const m of s.matchAll(/([\d.]+)\s*(seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d)\b/g)){const n=Number(m[1]);if(!Number.isFinite(n))continue;hit=true;const u=m[2];if(u.startsWith("d"))total+=n*86400;else if(u.startsWith("h"))total+=n*3600;else if(u.startsWith("m"))total+=n*60;else total+=n;}return hit?total:null;}
function entries(x:any,prefix=""):Array<{k:string,v:any}>{const out:Array<{k:string,v:any}>=[];if(Array.isArray(x)){for(let i=0;i<x.length;i++)out.push(...entries(x[i],`${prefix}[${i}]`));return out;}if(x&&typeof x==="object"){for(const [k,v] of Object.entries(x)){const p=prefix?`${prefix}.${k}`:k;if(v&&typeof v==="object")out.push(...entries(v,p));else out.push({k:p.toLowerCase(),v});}}return out;}
function pickByKeys(x:any,patterns:RegExp[],parser:(v:any)=>number|null=num){for(const e of entries(x)){if(patterns.some(p=>p.test(e.k))){const n=parser(e.v);if(n!=null)return n;}}return null;}
function normalizeRate(v:number|null){if(v==null)return null;return v>1?v/100:v;}
function summarize(trading:any,total:any,tokens:any){let winRate=pickByKeys(trading,[/(^|\.)win[_-]?rate$/,/(^|\.)token[_-]?winrate$/,/(^|\.)winrate$/]);winRate=normalizeRate(winRate);let medianHoldSeconds=pickByKeys(trading,[/median.*hold.*seconds/,/median.*holding.*seconds/]);if(medianHoldSeconds==null)medianHoldSeconds=pickByKeys(trading,[/median.*hold/,/median.*holding/],parseDuration);const tokensTraded=pickByKeys(trading,[/(^|\.)(tokens[_-]?traded|token[_-]?count|total[_-]?tokens)$/]);const realizedPnl=pickByKeys(total,[/realized.*pnl/,/total.*pnl/])??pickByKeys(trading,[/realized.*pnl/]);let realizedRoi=pickByKeys(total,[/realized.*roi/,/(^|\.)roi$/])??pickByKeys(trading,[/realized.*roi/]);realizedRoi=normalizeRate(realizedRoi);let tokenRows=0;if(Array.isArray(tokens))tokenRows=tokens.length;else if(Array.isArray(tokens?.data))tokenRows=tokens.data.length;else if(Array.isArray(tokens?.items))tokenRows=tokens.items.length;return{winRate,medianHoldSeconds,tokensTraded,realizedPnl,realizedRoi,tokenRows};}
async function cielo(path:string,query:string){if(!CIELO_API_KEY)throw new Error("CIELO_API_KEY missing");const url=`${BASE}${path}${query}`;for(let a=0;a<3;a++){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{headers:{"X-API-KEY":CIELO_API_KEY},signal:c.signal});const text=await r.text();if(r.status===202){if(a<2){await sleep(10000);continue;}throw new Error("202:data_not_ready");}if(!r.ok)throw new Error(`${r.status}:${text.slice(0,160)}`);return text?JSON.parse(text):{};}finally{clearTimeout(t);}}throw new Error("cielo request failed");}
function validate(candidate:any,s:any){const reasons:string[]=[];let status:GateStatus="PASS";const rank:Record<GateStatus,number>={UNKNOWN:0,PASS:1,SIGNAL_ONLY:2,REJECT:3};const downgrade=(next:GateStatus)=>{if(rank[next]>rank[status])status=next;};const scoutMed=num(candidate?.hold?.medianHoldSeconds),closed=num(candidate?.hold?.closedHolds)||0,externalMed=s.medianHoldSeconds as number|null,wr=s.winRate as number|null,tok=s.tokensTraded as number|null;
 if(externalMed==null&&wr==null&&tok==null)return{status:"UNKNOWN" as GateStatus,reasons:["cielo_fields_unparsed"]};
 if(externalMed!=null&&externalMed<600){downgrade("REJECT");reasons.push("cielo_median_hold_under_10m");}
 else if(externalMed!=null&&externalMed<3600){downgrade("SIGNAL_ONLY");reasons.push("cielo_median_hold_under_1h");}
 else if(externalMed!=null&&externalMed<21600){downgrade("SIGNAL_ONLY");reasons.push("cielo_median_hold_under_6h");}
 if(wr!=null&&tok!=null&&tok>=20&&wr<.20){downgrade("REJECT");reasons.push("cielo_win_rate_under_20pct");}
 else if(wr!=null&&tok!=null&&tok>=20&&wr<.30){downgrade("SIGNAL_ONLY");reasons.push("cielo_win_rate_under_30pct");}
 if(scoutMed!=null&&externalMed!=null&&externalMed>0){const ratio=Math.max(scoutMed/externalMed,externalMed/scoutMed);if(ratio>=3){downgrade("SIGNAL_ONLY");reasons.push(`hold_median_discrepancy_${ratio.toFixed(1)}x`);}}
 if(tok!=null&&tok>=20&&closed>0){const coverage=closed/tok;if(coverage<.25){downgrade("SIGNAL_ONLY");reasons.push(`reconstructed_sample_coverage_${(coverage*100).toFixed(1)}pct`);}}
 if(!reasons.length)reasons.push("cielo_external_validation_pass");return{status,reasons};}

export async function runCieloValidation(){const startedAt=new Date().toISOString();if(!CIELO_API_KEY){console.log(JSON.stringify({event:"shark_scout_cielo_validation_skipped",reason:"CIELO_API_KEY_missing"}));return;}
 let report:AnyObj,cp:AnyObj;try{report=JSON.parse(await fs.readFile(REPORT_PATH,"utf8"));cp=JSON.parse(await fs.readFile(CHECKPOINT_PATH,"utf8"));}catch(e){console.log(JSON.stringify({event:"shark_scout_cielo_validation_skipped",reason:"gauntlet_files_unavailable",error:String(e)}));return;}
 const candidates=Array.isArray(report.deepDive)?report.deepDive:[];const validations:any[]=[];for(const c of candidates){const address=String(c?.address||"");if(!address)continue;try{const [trading,total,tokens]=await Promise.all([cielo(`/${address}/trading-stats`,"?days=30d"),cielo(`/${address}/pnl/total-stats`,"?timeframe=30d&chains=solana"),cielo(`/${address}/pnl/tokens`,"?timeframe=30d&chain=solana")]);const summary=summarize(trading,total,tokens),decision=validate(c,summary),external={provider:"cielo",timeframe:"30d",checkedAt:new Date().toISOString(),...summary,...decision};validations.push({address,...external});const r=cp?.results?.[address];if(r){r.externalValidation=external;if(decision.status==="REJECT"||decision.status==="SIGNAL_ONLY"){r.verdict={status:decision.status,stage:"cielo_external_validation",reasons:[...(r.verdict?.reasons||[]),...decision.reasons]};}}}catch(e){validations.push({address,provider:"cielo",timeframe:"30d",status:"UNKNOWN",reasons:["cielo_request_error"],error:String(e).slice(0,220)});}}
 const current=Object.values(cp?.results||{}) as any[],counts=current.reduce((a:any,x:any)=>{const s=x?.verdict?.status||"UNKNOWN";a[s]=(a[s]||0)+1;return a;},{});const stillDeep=current.filter(x=>x?.verdict?.status==="DEEP_DIVE").sort((a,b)=>(b?.replay?.twoPerDay?.stress50NetSol||-999)-(a?.replay?.twoPerDay?.stress50NetSol||-999));report.cieloValidation={startedAt,finishedAt:new Date().toISOString(),candidatesChecked:validations.length,validations};report.deepDive=stillDeep.slice(0,25);report.counts=counts;report.note=`${report.note||""} Cielo 30D external validation is mandatory for DEEP_DIVE candidates; failed representativeness/copyability checks are downgraded in checkpoint.`.trim();cp.updatedAt=new Date().toISOString();await fs.writeFile(CHECKPOINT_PATH,JSON.stringify(cp));await fs.writeFile(REPORT_PATH,JSON.stringify(report));console.log(JSON.stringify({event:"shark_scout_cielo_validation_complete",startedAt,finishedAt:new Date().toISOString(),candidatesChecked:validations.length,counts,validations:validations.map(v=>({address:v.address,status:v.status,medianHoldSeconds:v.medianHoldSeconds,winRate:v.winRate,tokensTraded:v.tokensTraded,realizedPnl:v.realizedPnl,realizedRoi:v.realizedRoi,reasons:v.reasons,error:v.error}))}));}

if(import.meta.url===`file://${process.argv[1]}`)runCieloValidation().catch(e=>{console.error(JSON.stringify({event:"shark_scout_cielo_validation_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=0;});
