import { promises as fs } from "node:fs";
import path from "node:path";

const HELIUS_KEY=process.env.HELIUS_API_KEY?.trim();
const CP_PATH=process.env.SCOUT_GAUNTLET_STATE_PATH||"./data/gauntlet-state.json";
const STATE_PATH=process.env.SCOUT_DIP_SHADOW_STATE_PATH||"./data/dip-shadow-state.json";
const OUT_PATH=process.env.SCOUT_DIP_SHADOW_REPORT_PATH||"./data/dip-shadow-report.json";
const IAN="ianCETBFexGgK8TA3gSLeAaNiLMsJPgUN1H44jhxQtB";
const SIX_MZ="6mzEFZ458A6qcaQLgtBuYYaGJ1qN5tz2Wsr6PC1fLFzx";
const FOCUS=(process.env.DIP_SHADOW_FOCUS||`${IAN},${SIX_MZ}`).split(",").map(x=>x.trim()).filter(Boolean);
const MAX_WALLETS=Math.max(1,Math.min(12,Number(process.env.DIP_SHADOW_MAX_WALLETS||6)));
const FOLLOW_SIZE=Number(process.env.DIP_SHADOW_TRADE_SIZE_SOL||0.075);
const HORIZON_HOURS=Math.max(1,Math.min(168,Number(process.env.DIP_SHADOW_HORIZON_HOURS||24)));
const LEVELS=[0,10,20,30,40,50];
const ODIN_RATE=.01,TIP_RATE=.003,NETWORK=.00015;
const WSOL="So11111111111111111111111111111111111111112",USDC="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",USDT="Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB";
const QUOTES=new Set([WSOL,USDC,USDT]);

type AnyObj=Record<string,any>;
type Ev={signature:string;timestamp:number;side:"BUY"|"SELL";mint:string;qty:number|null;quoteSol:number|null};
type Branch={label:string;dipPct:number;status:"WATCHING"|"OPEN"|"CLOSED"|"EXPIRED";triggeredAt?:string;triggerTimestamp?:number;entryPriceSol?:number;paperQtyInitial?:number;paperQtyRemaining?:number;entryCostSol?:number;netProceedsSol?:number;sourceQtyRemaining?:number;closedAt?:string;netPnlSol?:number;returnPct?:number;reason?:string;minObservedPriceSol?:number;maxObservedPriceSol?:number;maxDrawdownFromSignalPct?:number;marketAtTrigger?:any};
type Opportunity={id:string;wallet:string;mint:string;sourceBuySignature:string;sourceBuyTimestamp:number;sourceQtyInitial:number;sourceQtyRemaining:number;sourcePriceSol:number;status:"ACTIVE"|"CLOSED"|"EXPIRED";sourceExitStarted:boolean;sourceAddedAfterSignal:boolean;expiresTimestamp:number;branches:Record<string,Branch>;snapshots:number;lastMarket?:any};

function now(){return new Date().toISOString();}
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:null;}
async function read(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomic(file:string,data:any){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(data));await fs.rename(tmp,file);}
function nativeSol(x:any){const v=n(x?.amount);return v==null?null:v/1e9;}
function entryCost(size:number){return size+Math.max(size*ODIN_RATE,.001)+size*TIP_RATE+NETWORK;}
function sellNet(gross:number){return gross-Math.max(gross*ODIN_RATE,.001)-gross*TIP_RATE-NETWORK;}
function quote(tx:any,wallet:string,dir:"out"|"in"){let total=0,seen=false;for(const x of tx?.nativeTransfers||[]){const hit=dir==="out"?x?.fromUserAccount===wallet:x?.toUserAccount===wallet;if(hit){const v=nativeSol(x);if(v!=null){total+=v;seen=true;}}}for(const x of tx?.tokenTransfers||[]){if(x?.mint!==WSOL)continue;const hit=dir==="out"?x?.fromUserAccount===wallet:x?.toUserAccount===wallet;if(hit){const v=n(x?.tokenAmount);if(v!=null){total+=v;seen=true;}}}return seen?total:null;}
function events(rows:any[],wallet:string){const out:Ev[]=[];for(const tx of rows){const ts=Number(tx?.timestamp);if(!Number.isFinite(ts))continue;const sw=tx?.events?.swap;let buys:any[]=[],sells:any[]=[];if(sw){buys=(sw.tokenOutputs||[]).filter((x:any)=>x?.userAccount===wallet&&!QUOTES.has(x?.mint));sells=(sw.tokenInputs||[]).filter((x:any)=>x?.userAccount===wallet&&!QUOTES.has(x?.mint));}if(!buys.length&&!sells.length){for(const x of tx?.tokenTransfers||[]){if(!x?.mint||QUOTES.has(x.mint))continue;if(x?.toUserAccount===wallet&&x?.fromUserAccount!==wallet)buys.push(x);if(x?.fromUserAccount===wallet&&x?.toUserAccount!==wallet)sells.push(x);}}const bq=nativeSol(sw?.nativeInput)??quote(tx,wallet,"out"),sq=nativeSol(sw?.nativeOutput)??quote(tx,wallet,"in");if(buys.length===1){const x=buys[0];out.push({signature:String(tx?.signature||""),timestamp:ts,side:"BUY",mint:String(x?.mint||""),qty:n(x?.tokenAmount??x?.rawTokenAmount?.tokenAmount),quoteSol:bq});}if(sells.length===1){const x=sells[0];out.push({signature:String(tx?.signature||""),timestamp:ts,side:"SELL",mint:String(x?.mint||""),qty:n(x?.tokenAmount??x?.rawTokenAmount?.tokenAmount),quoteSol:sq});}}return out.sort((a,b)=>a.timestamp-b.timestamp);}
async function helius(address:string){if(!HELIUS_KEY)return[];const q=new URLSearchParams({"api-key":HELIUS_KEY,limit:"100",type:"SWAP"});const c=new AbortController(),t=setTimeout(()=>c.abort(),25000);try{const r=await fetch(`https://api.helius.xyz/v0/addresses/${address}/transactions?${q}`,{signal:c.signal});if(!r.ok)throw new Error(`${r.status}:${(await r.text()).slice(0,120)}`);const x=await r.json();return Array.isArray(x)?x:[];}finally{clearTimeout(t);}}
async function market(mint:string){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);const r=await fetch(`https://api.dexscreener.com/latest/dex/tokens/${mint}`,{signal:c.signal});const x:any=await r.json();clearTimeout(t);if(!r.ok)return null;const pairs=(Array.isArray(x?.pairs)?x.pairs:[]).filter((p:any)=>p?.chainId==="solana"&&p?.baseToken?.address===mint&&p?.quoteToken?.address===WSOL).sort((a:any,b:any)=>Number(b?.liquidity?.usd||0)-Number(a?.liquidity?.usd||0));const p=pairs[0];if(!p)return null;return{priceSol:n(p.priceNative),priceUsd:n(p.priceUsd),marketCapUsd:n(p.marketCap)??n(p.fdv),liquidityUsd:n(p?.liquidity?.usd),dexId:p.dexId||null,pairAddress:p.pairAddress||null,capturedAt:now()};}catch{return null;}}
function makeBranch(level:number):Branch{return{label:level===0?"COPY_NOW":`DIP_${level}`,dipPct:level,status:level===0?"OPEN":"WATCHING"};}
function branchSummary(opps:Opportunity[],label:string){const xs=opps.map(o=>o.branches[label]).filter(Boolean),closed=xs.filter(b=>b.status==="CLOSED"),open=xs.filter(b=>b.status==="OPEN"),expired=xs.filter(b=>b.status==="EXPIRED"),pnl=closed.reduce((a,b)=>a+Number(b.netPnlSol||0),0),wins=closed.filter(b=>Number(b.netPnlSol)>0).length;return{label,eligible:xs.length,triggered:closed.length+open.length,open:open.length,closed:closed.length,expired:expired.length,triggerRate:xs.length?(closed.length+open.length)/xs.length:null,realizedNetSol:pnl,winRate:closed.length?wins/closed.length:null};}

async function main(){const startedAt=now(),cp=await read(CP_PATH,{results:{}}),s=await read(STATE_PATH,{schemaVersion:1,enrollments:{},seen:{},opportunities:{},ledger:[]});s.schemaVersion=1;s.enrollments||={};s.seen||={};s.opportunities||={};s.ledger||=[];const promoted=Object.entries(cp?.results||{}).filter(([,r0])=>["DEEP_DIVE","ODIN_PROSPECT"].includes(String((r0 as AnyObj)?.canonicalOverlay?.status||""))).map(([a])=>a),targets=[...new Set([...FOCUS,...promoted])].slice(0,MAX_WALLETS),errors:string[]=[];
 for(const wallet of targets){let rows:any[]=[];try{rows=await helius(wallet);}catch(e){errors.push(`${wallet}:${e instanceof Error?e.message:String(e)}`);continue;}const sigs=rows.map(x=>String(x?.signature||"")).filter(Boolean);if(!s.enrollments[wallet]){s.enrollments[wallet]={enrolledAt:now(),baselineSignatures:sigs.length};s.seen[wallet]=Object.fromEntries(sigs.map(x=>[x,true]));continue;}const ev=events(rows,wallet).filter(x=>!s.seen[wallet]?.[x.signature]);for(const e of ev){s.seen[wallet]||={};s.seen[wallet][e.signature]=true;if(e.qty==null||e.quoteSol==null||e.qty<=0||e.quoteSol<=0){s.ledger.push({action:"UNUSABLE_SIGNAL",wallet,mint:e.mint,side:e.side,signature:e.signature,sourceTimestamp:e.timestamp,reason:"SOURCE_QUOTE_OR_QTY_UNKNOWN"});continue;}const sourcePriceSol=e.quoteSol/e.qty;
   if(e.side==="BUY"){const active=Object.values(s.opportunities as Record<string,Opportunity>).filter((o:any)=>o.wallet===wallet&&o.mint===e.mint&&o.status==="ACTIVE") as Opportunity[];if(active.length){for(const o of active)o.sourceAddedAfterSignal=true;s.ledger.push({action:"SOURCE_ADD",wallet,mint:e.mint,signature:e.signature,sourceTimestamp:e.timestamp,sourcePriceSol});continue;}const id=`${wallet}|${e.signature}`;const branches:Record<string,Branch>={};for(const level of LEVELS)branches[level===0?"COPY_NOW":`DIP_${level}`]=makeBranch(level);const nowBranch=branches.COPY_NOW;nowBranch.triggeredAt=new Date(e.timestamp*1000).toISOString();nowBranch.triggerTimestamp=e.timestamp;nowBranch.entryPriceSol=sourcePriceSol;nowBranch.paperQtyInitial=FOLLOW_SIZE/sourcePriceSol;nowBranch.paperQtyRemaining=nowBranch.paperQtyInitial;nowBranch.entryCostSol=entryCost(FOLLOW_SIZE);nowBranch.netProceedsSol=0;nowBranch.sourceQtyRemaining=e.qty;nowBranch.minObservedPriceSol=sourcePriceSol;nowBranch.maxObservedPriceSol=sourcePriceSol;nowBranch.maxDrawdownFromSignalPct=0;const op:Opportunity={id,wallet,mint:e.mint,sourceBuySignature:e.signature,sourceBuyTimestamp:e.timestamp,sourceQtyInitial:e.qty,sourceQtyRemaining:e.qty,sourcePriceSol,status:"ACTIVE",sourceExitStarted:false,sourceAddedAfterSignal:false,expiresTimestamp:e.timestamp+HORIZON_HOURS*3600,branches,snapshots:0};s.opportunities[id]=op;s.ledger.push({action:"OPPORTUNITY_OPEN",id,wallet,mint:e.mint,signature:e.signature,sourceTimestamp:e.timestamp,sourcePriceSol,horizonHours:HORIZON_HOURS});}
   else {const opps=Object.values(s.opportunities as Record<string,Opportunity>).filter((o:any)=>o.wallet===wallet&&o.mint===e.mint&&o.status==="ACTIVE") as Opportunity[];for(const o of opps){o.sourceExitStarted=true;const soldQty=Math.min(e.qty,o.sourceQtyRemaining);o.sourceQtyRemaining=Math.max(0,o.sourceQtyRemaining-soldQty);for(const b of Object.values(o.branches)){if(b.status==="WATCHING"){b.status="EXPIRED";b.reason="SOURCE_EXIT_BEFORE_DIP";continue;}if(b.status!=="OPEN"||!b.paperQtyInitial||!b.paperQtyRemaining||!b.sourceQtyRemaining)continue;const branchSold=Math.min(soldQty,b.sourceQtyRemaining);const frac=branchSold/o.sourceQtyInitial;const paperSellQty=Math.min(b.paperQtyRemaining,b.paperQtyInitial*frac);const gross=paperSellQty*sourcePriceSol;b.paperQtyRemaining=Math.max(0,b.paperQtyRemaining-paperSellQty);b.sourceQtyRemaining=Math.max(0,b.sourceQtyRemaining-branchSold);b.netProceedsSol=Number(b.netProceedsSol||0)+sellNet(gross);if(b.paperQtyRemaining<=b.paperQtyInitial*.1||b.sourceQtyRemaining<=o.sourceQtyInitial*.1){b.status="CLOSED";b.closedAt=new Date(e.timestamp*1000).toISOString();b.netPnlSol=Number(b.netProceedsSol||0)-Number(b.entryCostSol||0);b.returnPct=Number(b.entryCostSol)>0?b.netPnlSol/Number(b.entryCostSol):undefined;}}if(o.sourceQtyRemaining<=o.sourceQtyInitial*.1){o.status="CLOSED";s.ledger.push({action:"OPPORTUNITY_CLOSED",id:o.id,wallet,mint:o.mint,signature:e.signature,sourceTimestamp:e.timestamp});}}}}
 }
 const active=Object.values(s.opportunities as Record<string,Opportunity>).filter((o:any)=>o.status==="ACTIVE") as Opportunity[];for(const o of active){const ts=Math.floor(Date.now()/1000);if(ts>o.expiresTimestamp&&!o.sourceExitStarted){for(const b of Object.values(o.branches))if(b.status==="WATCHING"){b.status="EXPIRED";b.reason="HORIZON_EXPIRED";}}let md:any=null;try{md=await market(o.mint);}catch{}if(!md?.priceSol)continue;o.snapshots++;o.lastMarket=md;const drawdownPct=(md.priceSol/o.sourcePriceSol-1)*100;for(const b of Object.values(o.branches)){if(b.status==="OPEN"){b.minObservedPriceSol=Math.min(b.minObservedPriceSol??md.priceSol,md.priceSol);b.maxObservedPriceSol=Math.max(b.maxObservedPriceSol??md.priceSol,md.priceSol);b.maxDrawdownFromSignalPct=Math.min(b.maxDrawdownFromSignalPct??0,drawdownPct);continue;}if(b.status!=="WATCHING"||o.sourceExitStarted||ts>o.expiresTimestamp)continue;if(drawdownPct<=-b.dipPct){b.status="OPEN";b.triggeredAt=now();b.triggerTimestamp=ts;b.entryPriceSol=md.priceSol;b.paperQtyInitial=FOLLOW_SIZE/md.priceSol;b.paperQtyRemaining=b.paperQtyInitial;b.entryCostSol=entryCost(FOLLOW_SIZE);b.netProceedsSol=0;b.sourceQtyRemaining=o.sourceQtyRemaining;b.minObservedPriceSol=md.priceSol;b.maxObservedPriceSol=md.priceSol;b.maxDrawdownFromSignalPct=drawdownPct;b.marketAtTrigger=md;s.ledger.push({action:"DIP_TRIGGER",id:o.id,wallet:o.wallet,mint:o.mint,label:b.label,dipPct:b.dipPct,sourceTimestamp:o.sourceBuyTimestamp,triggeredAt:b.triggeredAt,observedDrawdownPct:drawdownPct,entryPriceSol:md.priceSol,marketAtTrigger:md});}}}
 if(s.ledger.length>10000)s.ledger=s.ledger.slice(-10000);s.updatedAt=now();await atomic(STATE_PATH,s);const opps=Object.values(s.opportunities as Record<string,Opportunity>) as Opportunity[];const report={schemaVersion:1,event:"shark_scout_dip_shadow_complete",startedAt,finishedAt:now(),targets,horizonHours:HORIZON_HOURS,tradeSizeSol:FOLLOW_SIZE,levels:LEVELS,opportunities:opps.length,active:opps.filter(o=>o.status==="ACTIVE").length,closed:opps.filter(o=>o.status==="CLOSED").length,branches:LEVELS.map(l=>branchSummary(opps,l===0?"COPY_NOW":`DIP_${l}`)),wallets:targets.map(wallet=>({wallet,opportunities:opps.filter(o=>o.wallet===wallet).length,active:opps.filter(o=>o.wallet===wallet&&o.status==="ACTIVE").length,branches:LEVELS.map(l=>branchSummary(opps.filter(o=>o.wallet===wallet),l===0?"COPY_NOW":`DIP_${l}`))})),errors,notes:["Prospective only: existing signatures are baselined at wallet enrollment.","Every new-position source BUY gets COPY_NOW plus 10/20/30/40/50% dip branches; source adds are tagged instead of creating a second entry experiment.","Dip branches expire when the source begins selling or after the configured horizon.","Triggered branches follow the source sell lifecycle and use 0.075 SOL fixed sizing plus modeled Odin/tip/network costs.","Price-path sampling currently occurs on the hourly Shark Scout cadence; a dip between hourly observations can be missed. Do not interpret this as intrahour precision.","Only the most liquid WSOL-quoted Solana pair is used for dip observation to keep price units consistent with source SOL execution."]};await atomic(OUT_PATH,report);console.log(JSON.stringify(report));}

main().catch(e=>{console.error(JSON.stringify({event:"shark_scout_dip_shadow_failed",at:now(),error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});
