import { promises as fs } from "node:fs";
import path from "node:path";

const CP_PATH=process.env.SCOUT_GAUNTLET_STATE_PATH||"/data/gauntlet-state.json";
const STATE_PATH=process.env.SCOUT_STATE_PATH||"/data/shark-state.json";
const QUEUE_PATH=process.env.SCOUT_DEEP_DIVE_QUEUE_PATH||"/data/deep-dive-queue.json";
const OUT_PATH=process.env.SCOUT_EVIDENCE_FUNNEL_PATH||"/data/evidence-funnel.json";
const TOP=Math.max(5,Math.min(50,Number(process.env.EVIDENCE_FUNNEL_TOP||15)));
type AnyObj=Record<string,any>;
function now(){return new Date().toISOString();}
function n(v:any,d=0){const x=Number(v);return Number.isFinite(x)?x:d;}
function finite(v:any){const x=Number(v);return Number.isFinite(x)?x:null;}
async function readJson(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomic(file:string,data:any){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(data));await fs.rename(tmp,file);}
function replay(r:any){const trips=Array.isArray(r?.hold?.roundTrips)?r.hold.roundTrips:[],nets=trips.map((x:any)=>finite(x?.followerNetSol)).filter((x:any):x is number=>x!==null),s50=trips.map((x:any)=>finite(x?.stress50NetSol)).filter((x:any):x is number=>x!==null);return{trades:nets.length,net:nets.length?nets.reduce((a,b)=>a+b,0):null,stress50:s50.length?s50.reduce((a,b)=>a+b,0):null};}
function quality(r:any,w:any){const closed=n(r?.hold?.closedHolds),buys=n(r?.hold?.buyEvents),partial=Boolean(r?.heliusCoveragePartial),disc=n(r?.discoveryTokens||w?.tokens?.length),coverage=buys>0?Math.min(1,closed/buys):null;const reasons:string[]=[];let risk=0;if(partial){risk=2;reasons.push("helius_history_partial");}if(closed<10){risk=2;reasons.push("closed_sample_lt_10");}else if(closed<20){risk=Math.max(risk,1);reasons.push("closed_sample_lt_20");}if(disc<2){risk=Math.max(risk,1);reasons.push("single_discovery_context");}if(coverage!=null&&coverage<.35){risk=2;reasons.push("low_close_to_buy_coverage");}return{risk:risk>=2?"HIGH":risk===1?"MEDIUM":"LOW",reasons,coverage,closed,buys,discoveryContexts:disc};}
function blockers(r:any,w:any){const rp=replay(r),q=quality(r,w),med=finite(r?.hold?.medianHoldSeconds),out:string[]=[];if(med!=null&&med<600)out.push("HARD_FAST_UNDER_10M");else if((med??0)<3600)out.push("MEDIAN_HOLD_UNDER_1H");if(q.risk==="HIGH")out.push(...q.reasons.map(x=>`SAMPLE:${x}`));if(rp.trades<10)out.push("REPLAY_TRADES_LT_10");if(rp.net==null)out.push("REPLAY_NET_UNKNOWN");else if(rp.net<=0)out.push("REPLAY_NET_NONPOSITIVE");if(rp.stress50==null)out.push("STRESS50_UNKNOWN");else if(rp.stress50<=0)out.push("STRESS50_NONPOSITIVE");return{rp,q,med,out};}
function nearPassScore(x:any){let s=0;if(x.med!=null&&x.med>=3600)s+=25;if(x.rp.trades>=10)s+=20;if((x.rp.net??-1)>0)s+=25;if((x.rp.stress50??-1)>0)s+=20;if(x.q.risk==="MEDIUM")s+=6;if(x.q.risk==="LOW")s+=10;if(x.q.coverage!=null)s+=Math.round(Math.min(1,x.q.coverage)*10);return s;}
export async function runEvidenceFunnel(){const startedAt=now(),[cp,state,queue]=await Promise.all([readJson(CP_PATH,{results:{}}),readJson(STATE_PATH,{wallets:{}}),readJson(QUEUE_PATH,{queue:[]})]);const rows:any[]=[];const statusCounts:AnyObj={},blockerCounts:AnyObj={};for(const [address,r0] of Object.entries(cp?.results||{})){const r=r0 as AnyObj,w=state?.wallets?.[address]||{},b=blockers(r,w),status=String(r?.verdict?.status||w?.status||"UNKNOWN");statusCounts[status]=(statusCounts[status]||0)+1;for(const x of b.out)blockerCounts[x]=(blockerCounts[x]||0)+1;const actionable=!b.out.length;rows.push({address,status,actionable,nearPassScore:nearPassScore(b),medianHoldHours:b.med!=null?b.med/3600:null,replay:b.rp,sampleQuality:b.q,blockers:b.out,evaluatedAt:r?.evaluatedAt||null});}
rows.sort((a,b)=>Number(b.actionable)-Number(a.actionable)||b.nearPassScore-a.nearPassScore||Number(b.replay.net??-999)-Number(a.replay.net??-999));const actionable=rows.filter(x=>x.actionable),sampleBlocked=rows.filter(x=>x.blockers.some((b:string)=>b.startsWith("SAMPLE:"))&&(x.replay.net??-1)>0&&(x.replay.stress50??-1)>0&&Number(x.medianHoldHours||0)>=1),replayBlocked=rows.filter(x=>x.blockers.includes("REPLAY_TRADES_LT_10")&&Number(x.medianHoldHours||0)>=1&&x.sampleQuality.risk!=="HIGH");const out={schemaVersion:1,event:"shark_scout_evidence_funnel_complete",startedAt,finishedAt:now(),evaluated:rows.length,statusCounts,actionableCount:actionable.length,positiveReplayCount:rows.filter(x=>(x.replay.net??-1)>0).length,stressSurvivorCount:rows.filter(x=>(x.replay.stress50??-1)>0).length,sampleQualityBlockedPositiveCount:sampleBlocked.length,replaySampleBlockedCount:replayBlocked.length,blockerCounts:Object.entries(blockerCounts).sort((a:any,b:any)=>b[1]-a[1]).map(([blocker,count])=>({blocker,count})),topNearPasses:rows.filter(x=>!x.actionable).slice(0,TOP),topSampleQualityBlocks:sampleBlocked.slice(0,TOP),topReplayBlocks:replayBlocked.slice(0,TOP),deepDiveQueue:Array.isArray(queue?.queue)?queue.queue.slice(0,TOP):[],notes:["This report explains funnel attrition; it does not relax gauntlet standards.","Near-pass score prioritizes investigation only and is not a live-trading promotion score.","Sample-quality blockers are separated from demonstrated bad follower economics so provider budget can target resolvable uncertainty."]};await atomic(OUT_PATH,out);console.log(JSON.stringify(out));return out;}
if(import.meta.url===`file://${process.argv[1]}`)runEvidenceFunnel().catch(e=>{console.error(JSON.stringify({event:"shark_scout_evidence_funnel_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});