import { promises as fs } from "node:fs";
import path from "node:path";

const HELIUS_API_KEY = process.env.HELIUS_API_KEY?.trim();
const VYBE_API_KEY = process.env.VYBE_API_KEY?.trim();
const STATE_PATH = process.env.SCOUT_STATE_PATH || "./data/shark-state.json";
const CHECKPOINT_PATH = process.env.SCOUT_GAUNTLET_STATE_PATH || "./data/gauntlet-state.json";
const REPORT_PATH = process.env.SCOUT_GAUNTLET_PATH || "./data/latest-gauntlet.json";
const BATCH_SIZE = clamp(Number(process.env.GAUNTLET_BATCH_SIZE || 30), 5, 60);
const CONCURRENCY = clamp(Number(process.env.GAUNTLET_CONCURRENCY || 4), 1, 8);
const HELIUS_PAGES = clamp(Number(process.env.GAUNTLET_HELIUS_PAGES || 3), 1, 5);
const TIMEOUT_MS = clamp(Number(process.env.REQUEST_TIMEOUT_MS || 15000), 3000, 60000);
const FOLLOW_SIZE = 0.075;
const ODIN_RATE = 0.01;
const TIP_RATE = 0.003;
const NETWORK_PER_LEG = 0.00015;
const WSOL = "So11111111111111111111111111111111111111112";
const USDC = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
const USDT = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB";
const QUOTES = new Set([WSOL, USDC, USDT]);

type Wallet = { address:string; status?:string; tokens?:string[]; providers?:string[]; rediscoveryCount?:number; tags?:string[]; lastSeen?:string };
type RoundTrip = { mint:string; holdSeconds:number; buySol:number|null; sellSol:number|null; sourceRoi:number|null; followerNetSol:number|null; followerRoi:number|null; stress50NetSol:number|null; stress75NetSol:number|null };
type Result = { address:string; fingerprint:string; evaluatedAt:string; discoveryTokens:number; rediscoveryCount:number; providers:string[]; heliusTransactions:number; heliusSwaps:number; heliusCoveragePartial:boolean; vybeTrades30d:number; vybeError:string|null; hold:any; robustness:any; verdict:any };
type Checkpoint = { schemaVersion:number; updatedAt:string; results:Record<string,Result>; runs:Array<any> };

function clamp(n:number,min:number,max:number){ return Math.max(min,Math.min(max,Number.isFinite(n)?Math.floor(n):min)); }
function median(v:number[]):number|null { if(!v.length)return null; const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2); return a.length%2?a[m]!:(a[m-1]!+a[m]!)/2; }
function quantile(v:number[],p:number):number|null { if(!v.length)return null; const a=[...v].sort((x,y)=>x-y); return a[Math.min(a.length-1,Math.floor((a.length-1)*p))]!; }
function score(w:Wallet){ return (w.tokens?.length||0)*1000 + Math.min(w.rediscoveryCount||0,500); }
function fingerprint(w:Wallet){ return `${(w.tokens||[]).slice().sort().join(",")}|${w.rediscoveryCount||0}|${w.lastSeen||""}`; }
function badTag(tags:string[]=[]){ const s=tags.join(" ").toLowerCase(); for(const x of ["sniper","bundler","insider","developer","bot","mev","exchange","cex"]) if(s.includes(x))return x; return null; }
async function fetchJson(url:string,init:RequestInit={}){ const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS); try{ const r=await fetch(url,{...init,signal:c.signal}); const text=await r.text(); if(!r.ok)throw new Error(`${r.status}:${text.slice(0,180)}`); return text?JSON.parse(text):null; } finally { clearTimeout(t); } }
async function atomicSave(file:string,data:any){ await fs.mkdir(path.dirname(file),{recursive:true}); const tmp=`${file}.tmp`; await fs.writeFile(tmp,JSON.stringify(data,null,2)); await fs.rename(tmp,file); }
async function loadCheckpoint():Promise<Checkpoint>{ try{ const x=JSON.parse(await fs.readFile(CHECKPOINT_PATH,"utf8")); return {schemaVersion:3,updatedAt:x.updatedAt||new Date().toISOString(),results:x.results||{},runs:Array.isArray(x.runs)?x.runs:[]}; }catch{ return {schemaVersion:3,updatedAt:new Date().toISOString(),results:{},runs:[]}; } }

async function heliusHistory(address:string){ if(!HELIUS_API_KEY)return{rows:[] as any[],error:"HELIUS_API_KEY missing",partial:true}; const all:any[]=[]; let before:string|undefined; let partial=false; try{ for(let page=0;page<HELIUS_PAGES;page++){ const u=new URL(`https://api.helius.xyz/v0/addresses/${address}/transactions`); u.searchParams.set("api-key",HELIUS_API_KEY); u.searchParams.set("limit","100"); if(before)u.searchParams.set("before",before); const x=await fetchJson(u.toString()); if(!Array.isArray(x)||!x.length)break; all.push(...x); before=x[x.length-1]?.signature; if(x.length<100)break; if(page===HELIUS_PAGES-1 && x.length===100)partial=true; } return{rows:all,error:null,partial}; }catch(e){ return{rows:all,error:String(e),partial:true}; } }
async function vybeTrades(address:string){ if(!VYBE_API_KEY)return{rows:[] as any[],error:"VYBE_API_KEY missing"}; try{ const end=Math.floor(Date.now()/1000),start=end-30*86400,q=new URLSearchParams({authorityAddress:address,timeStart:String(start),timeEnd:String(end),limit:"500",page:"0",sortByAsc:"blockTime"}); const x=await fetchJson(`https://api.vybenetwork.xyz/v4/trades?${q}`,{headers:{"X-API-Key":VYBE_API_KEY}}); return{rows:Array.isArray(x?.data)?x.data:[],error:null}; }catch(e){ return{rows:[],error:String(e)}; } }
function nativeSol(x:any){ const n=Number(x?.amount); return Number.isFinite(n)?n/1e9:null; }
function followerEconomics(sourceRoi:number|null,retention=1){ if(sourceRoi==null)return{net:null,roi:null}; const buyFee=Math.max(FOLLOW_SIZE*ODIN_RATE,0.001),buyTip=FOLLOW_SIZE*TIP_RATE,buyTotal=FOLLOW_SIZE+buyFee+buyTip+NETWORK_PER_LEG; const grossExit=FOLLOW_SIZE*(1+sourceRoi*retention); const sellFee=Math.max(Math.max(grossExit,0)*ODIN_RATE,0.001),sellTip=Math.max(grossExit,0)*TIP_RATE,netExit=grossExit-sellFee-sellTip-NETWORK_PER_LEG,net=netExit-buyTotal; return{net,roi:net/buyTotal}; }
function holds(rows:any[],wallet:string){ const ordered=[...rows].filter(x=>x?.type==="SWAP"&&Number.isFinite(Number(x?.timestamp))).sort((a,b)=>Number(a.timestamp)-Number(b.timestamp)); const open=new Map<string,Array<{t:number;sol:number|null}>>(),rts:RoundTrip[]=[]; let buys=0,sells=0; for(const tx of ordered){ const ev=tx?.events?.swap; if(!ev)continue; const t=Number(tx.timestamp),outs=(ev.tokenOutputs||[]).filter((x:any)=>x?.userAccount===wallet&&!QUOTES.has(x?.mint)),ins=(ev.tokenInputs||[]).filter((x:any)=>x?.userAccount===wallet&&!QUOTES.has(x?.mint)); for(const o of outs){ buys++; const a=open.get(o.mint)||[]; a.push({t,sol:nativeSol(ev.nativeInput)}); open.set(o.mint,a); } for(const i of ins){ sells++; const a=open.get(i.mint)||[]; if(!a.length)continue; const b=a.shift()!,sell=nativeSol(ev.nativeOutput),src=b.sol&&sell!=null?(sell-b.sol)/b.sol:null,full=followerEconomics(src,1),stress50=followerEconomics(src,.5),stress75=followerEconomics(src,.25); rts.push({mint:i.mint,holdSeconds:Math.max(0,t-b.t),buySol:b.sol,sellSol:sell,sourceRoi:src,followerNetSol:full.net,followerRoi:full.roi,stress50NetSol:stress50.net,stress75NetSol:stress75.net}); open.set(i.mint,a); } }
 const hs=rts.map(x=>x.holdSeconds),fr=rts.map(x=>x.followerRoi).filter((x):x is number=>x!=null),nets=rts.map(x=>x.followerNetSol).filter((x):x is number=>x!=null),n50=rts.map(x=>x.stress50NetSol).filter((x):x is number=>x!=null),n75=rts.map(x=>x.stress75NetSol).filter((x):x is number=>x!=null); return{closedHolds:hs.length,medianHoldSeconds:median(hs),p25HoldSeconds:quantile(hs,.25),p75HoldSeconds:quantile(hs,.75),fastUnder10m:hs.filter(x=>x<600).length,slowOver6h:hs.filter(x=>x>=21600).length,idealOver12h:hs.filter(x=>x>=43200).length,buyEvents:buys,sellEvents:sells,estimatedFollowerTrades:fr.length,estimatedFollowerWinRate:fr.length?fr.filter(x=>x>0).length/fr.length:null,estimatedFollowerMedianRoi:median(fr),estimatedFollowerNetSol:nets.length?nets.reduce((a,b)=>a+b,0):null,stress50NetSol:n50.length?n50.reduce((a,b)=>a+b,0):null,stress75NetSol:n75.length?n75.reduce((a,b)=>a+b,0):null,roundTrips:rts.slice(-40)}; }
function robustness(h:any){ const nets=(h.roundTrips||[]).map((x:any)=>x.followerNetSol).filter((x:any)=>typeof x==="number") as number[]; const positive=nets.filter(x=>x>0),totalPositive=positive.reduce((a,b)=>a+b,0),largest=positive.length?Math.max(...positive):0; return{positiveTrades:positive.length,largestWinnerShare:totalPositive>0?largest/totalPositive:null,antiJackpotPass:totalPositive>0?largest/totalPositive<=0.6:null,stress50Positive:typeof h.stress50NetSol==="number"?h.stress50NetSol>0:null,stress75Positive:typeof h.stress75NetSol==="number"?h.stress75NetSol>0:null}; }
function verdict(w:Wallet,h:any,r:any,vybeRows:any[],errors:string[],partial:boolean){ const tag=badTag(w.tags); if(tag)return{status:"REJECT",stage:"hard_gate",reasons:[`bad_tag:${tag}`]}; const medh=h.medianHoldSeconds; if(medh!=null&&medh<600)return{status:"REJECT",stage:"hold_time",reasons:[`median_hold_${Math.round(medh)}s_under_10m`]}; if(medh!=null&&medh<3600)return{status:"SIGNAL_ONLY",stage:"hold_time",reasons:[`median_hold_${Math.round(medh/60)}m_under_1h`]}; const reasons:string[]=[]; if(partial)reasons.push("helius_history_window_partial"); if(h.closedHolds<5)reasons.push("closed_hold_sample_under_5"); if(medh==null)reasons.push("hold_time_unknown"); else if(medh<21600)reasons.push("median_hold_under_6h"); else if(medh<43200)reasons.push("median_hold_6h_plus"); else reasons.push("median_hold_12h_plus"); if(vybeRows.length>=400)reasons.push("high_activity_30d_400plus"); if((w.tokens?.length||0)<2)reasons.push("single_discovery_token"); else reasons.push(`cross_token_${w.tokens!.length}`); if(errors.length)reasons.push(...errors); if(h.estimatedFollowerTrades>=5&&h.estimatedFollowerNetSol!=null&&h.estimatedFollowerNetSol<=0)return{status:"REJECT",stage:"fixed_size_economics",reasons:[...reasons,"0.075_estimated_net_nonpositive"]}; if(r.antiJackpotPass===false)return{status:"REJECT",stage:"robustness",reasons:[...reasons,"largest_winner_over_60pct_positive_pnl"]}; if(medh!=null&&medh>=21600&&h.closedHolds>=5&&(w.tokens?.length||0)>=2&&h.estimatedFollowerNetSol>0&&r.antiJackpotPass===true&&r.stress50Positive===true)return{status:"DEEP_DIVE",stage:"pre_replay",reasons:[...reasons,"0.075_fee_model_positive","anti_jackpot_pass","50pct_alpha_retention_positive","needs_price_lag_liquidity_replay"]}; return{status:"UNKNOWN",stage:"insufficient_evidence",reasons}; }

async function evaluate(w:Wallet):Promise<Result>{ const [hx,vt]=await Promise.all([heliusHistory(w.address),vybeTrades(w.address)]); const h=holds(hx.rows,w.address),r=robustness(h),errors:string[]=[]; if(hx.error)errors.push("helius_history_error"); if(vt.error)errors.push("vybe_history_unavailable"); const v=verdict(w,h,r,vt.rows,errors,hx.partial); return{address:w.address,fingerprint:fingerprint(w),evaluatedAt:new Date().toISOString(),discoveryTokens:w.tokens?.length||0,rediscoveryCount:w.rediscoveryCount||0,providers:w.providers||[],heliusTransactions:hx.rows.length,heliusSwaps:hx.rows.filter(x=>x?.type==="SWAP").length,heliusCoveragePartial:hx.partial,vybeTrades30d:vt.rows.length,vybeError:vt.error,hold:h,robustness:r,verdict:v}; }

export async function runGauntlet(){ const startedAt=new Date().toISOString(),state=JSON.parse(await fs.readFile(STATE_PATH,"utf8")),cp=await loadCheckpoint(); const eligible=(Object.values(state.wallets||{}) as Wallet[]).filter(w=>w.status!=="REJECTED").sort((a,b)=>score(b)-score(a)); const pending=eligible.filter(w=>cp.results[w.address]?.fingerprint!==fingerprint(w)); const batch=pending.slice(0,BATCH_SIZE); let completedThisRun=0; for(let i=0;i<batch.length;i+=CONCURRENCY){ const wave=batch.slice(i,i+CONCURRENCY),results=await Promise.all(wave.map(evaluate)); for(const r of results)cp.results[r.address]=r; completedThisRun+=results.length; cp.updatedAt=new Date().toISOString(); await atomicSave(CHECKPOINT_PATH,cp); }
 const current=eligible.map(w=>cp.results[w.address]).filter((x):x is Result=>Boolean(x)); const counts=current.reduce((a:any,x:any)=>(a[x.verdict.status]=(a[x.verdict.status]||0)+1,a),{}),deep=current.filter(x=>x.verdict.status==="DEEP_DIVE").sort((a,b)=>(b.hold.estimatedFollowerNetSol||-999)-(a.hold.estimatedFollowerNetSol||-999)); const remaining=Math.max(eligible.length-current.length,0); const runSummary={startedAt,finishedAt:new Date().toISOString(),eligible:eligible.length,processedThisRun:completedThisRun,processedCumulative:current.length,remaining,counts}; cp.runs=[...cp.runs.slice(-99),runSummary]; cp.updatedAt=new Date().toISOString(); await atomicSave(CHECKPOINT_PATH,cp); const report={schemaVersion:3,generatedAt:new Date().toISOString(),...runSummary,note:"Resumable preliminary copyability gauntlet. DEEP_DIVE is not LIVE-TEST WORTHY: final promotion still requires exact raw economic reconstruction and historical source-to-copy price/lag/liquidity/slippage replay under Odin controls.",deepDive:deep.slice(0,25),results:current}; await atomicSave(REPORT_PATH,report); console.log(JSON.stringify({event:"shark_scout_gauntlet_complete",generatedAt:report.generatedAt,processedThisRun:completedThisRun,processedCumulative:current.length,remaining,counts,deepDive:deep.slice(0,10).map(x=>({address:x.address,medianHoldSeconds:x.hold.medianHoldSeconds,closedHolds:x.hold.closedHolds,discoveryTokens:x.discoveryTokens,estimatedFollowerNetSol:x.hold.estimatedFollowerNetSol,stress50NetSol:x.hold.stress50NetSol,largestWinnerShare:x.robustness.largestWinnerShare,reasons:x.verdict.reasons}))})); return report; }
if(import.meta.url===`file://${process.argv[1]}`)runGauntlet().catch(e=>{console.error(JSON.stringify({event:"shark_scout_gauntlet_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});
