import { promises as fs } from "node:fs";
import path from "node:path";

const HELIUS_API_KEY=process.env.HELIUS_API_KEY?.trim();
const VYBE_API_KEY=process.env.VYBE_API_KEY?.trim();
const STATE_PATH=process.env.SCOUT_STATE_PATH||"./data/shark-state.json";
const REPORT_PATH=process.env.SCOUT_GAUNTLET_PATH||"./data/latest-gauntlet.json";
const LIMIT=Math.max(10,Math.min(Number(process.env.GAUNTLET_WALLET_LIMIT||50),100));
const TIMEOUT_MS=Math.max(3000,Math.min(Number(process.env.REQUEST_TIMEOUT_MS||15000),60000));
const WSOL="So11111111111111111111111111111111111111112",USDC="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",USDT="Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB";
const QUOTES=new Set([WSOL,USDC,USDT]);
const FOLLOW_SIZE=0.075, ODIN_RATE=0.01, TIP_RATE=0.003, NETWORK_PER_LEG=0.00015;

type Wallet={address:string;status?:string;tokens?:string[];providers?:string[];rediscoveryCount?:number;tags?:string[]};
type RoundTrip={mint:string;holdSeconds:number;buySol:number|null;sellSol:number|null;sourceRoi:number|null;followerNetSol:number|null;followerRoi:number|null};
function med(v:number[]){if(!v.length)return null;const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]!:(a[m-1]!+a[m]!)/2;}
function q(v:number[],p:number){if(!v.length)return null;const a=[...v].sort((x,y)=>x-y);return a[Math.min(a.length-1,Math.floor((a.length-1)*p))]!;}
function score(w:Wallet){return(w.tokens?.length||0)*100+(w.providers?.length||0)*25+Math.min(w.rediscoveryCount||0,25);}
function badTag(tags:string[]=[]){const s=tags.join(" ").toLowerCase();for(const x of ["sniper","bundler","insider","developer","bot","mev","exchange","cex"])if(s.includes(x))return x;return null;}
async function fetchJson(url:string,init:RequestInit={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal}),text=await r.text();if(!r.ok)throw new Error(`${r.status}:${text.slice(0,180)}`);return text?JSON.parse(text):null;}finally{clearTimeout(t);}}
async function heliusHistory(address:string){if(!HELIUS_API_KEY)return{rows:[] as any[],error:"HELIUS_API_KEY missing"};const all:any[]=[];let before:string|undefined;try{for(let page=0;page<3;page++){const u=new URL(`https://api.helius.xyz/v0/addresses/${address}/transactions`);u.searchParams.set("api-key",HELIUS_API_KEY);u.searchParams.set("limit","100");if(before)u.searchParams.set("before",before);const x=await fetchJson(u.toString());if(!Array.isArray(x)||!x.length)break;all.push(...x);before=x[x.length-1]?.signature;if(x.length<100)break;}return{rows:all,error:null};}catch(e){return{rows:all,error:String(e)};}}
async function vybeTrades(address:string){if(!VYBE_API_KEY)return{rows:[] as any[],error:"VYBE_API_KEY missing"};try{const end=Math.floor(Date.now()/1000),start=end-30*86400,q=new URLSearchParams({authorityAddress:address,timeStart:String(start),timeEnd:String(end),limit:"500",page:"0",sortByAsc:"blockTime"});const x=await fetchJson(`https://api.vybenetwork.xyz/v4/trades?${q}`,{headers:{"X-API-Key":VYBE_API_KEY}});return{rows:Array.isArray(x?.data)?x.data:[],error:null};}catch(e){return{rows:[],error:String(e)};}}
function nativeSol(x:any){const n=Number(x?.amount);return Number.isFinite(n)?n/1e9:null;}
function followerEconomics(sourceRoi:number|null){if(sourceRoi==null)return{net:null,roi:null};const buyFee=Math.max(FOLLOW_SIZE*ODIN_RATE,0.001),buyTip=FOLLOW_SIZE*TIP_RATE,buyTotal=FOLLOW_SIZE+buyFee+buyTip+NETWORK_PER_LEG;const grossExit=FOLLOW_SIZE*(1+sourceRoi);const sellFee=Math.max(grossExit*ODIN_RATE,0.001),sellTip=grossExit*TIP_RATE,netExit=grossExit-sellFee-sellTip-NETWORK_PER_LEG,net=netExit-buyTotal;return{net,roi:net/buyTotal};}
function holds(rows:any[],wallet:string){const ordered=[...rows].filter(x=>x?.type==="SWAP"&&Number.isFinite(Number(x?.timestamp))).sort((a,b)=>Number(a.timestamp)-Number(b.timestamp));const open=new Map<string,Array<{t:number;sol:number|null}>>(),rts:RoundTrip[]=[];let buys=0,sells=0;for(const tx of ordered){const ev=tx?.events?.swap;if(!ev)continue;const t=Number(tx.timestamp),outs=(ev.tokenOutputs||[]).filter((x:any)=>x?.userAccount===wallet&&!QUOTES.has(x?.mint)),ins=(ev.tokenInputs||[]).filter((x:any)=>x?.userAccount===wallet&&!QUOTES.has(x?.mint));for(const o of outs){buys++;const a=open.get(o.mint)||[];a.push({t,sol:nativeSol(ev.nativeInput)});open.set(o.mint,a);}for(const i of ins){sells++;const a=open.get(i.mint)||[];if(a.length){const b=a.shift()!,sell=nativeSol(ev.nativeOutput),src=b.sol&&sell!=null?(sell-b.sol)/b.sol:null,fe=followerEconomics(src);rts.push({mint:i.mint,holdSeconds:Math.max(0,t-b.t),buySol:b.sol,sellSol:sell,sourceRoi:src,followerNetSol:fe.net,followerRoi:fe.roi});open.set(i.mint,a);}}}const hs=rts.map(x=>x.holdSeconds),fr=rts.map(x=>x.followerRoi).filter((x):x is number=>x!=null),nets=rts.map(x=>x.followerNetSol).filter((x):x is number=>x!=null);return{closedHolds:hs.length,medianHoldSeconds:med(hs),p25HoldSeconds:q(hs,.25),p75HoldSeconds:q(hs,.75),fastUnder10m:hs.filter(x=>x<600).length,slowOver6h:hs.filter(x=>x>=21600).length,idealOver12h:hs.filter(x=>x>=43200).length,buyEvents:buys,sellEvents:sells,estimatedFollowerTrades:fr.length,estimatedFollowerWinRate:fr.length?fr.filter(x=>x>0).length/fr.length:null,estimatedFollowerMedianRoi:med(fr),estimatedFollowerNetSol:nets.length?nets.reduce((a,b)=>a+b,0):null,roundTrips:rts.slice(-30)};}
function verdict(w:Wallet,h:any,vybe:any[],errors:string[]){const tag=badTag(w.tags);if(tag)return{status:"REJECT",stage:"hard_gate",reasons:[`bad_tag:${tag}`]};const medh=h.medianHoldSeconds;if(medh!=null&&medh<600)return{status:"REJECT",stage:"hold_time",reasons:[`median_hold_${Math.round(medh)}s_under_10m`]};if(medh!=null&&medh<3600)return{status:"SIGNAL_ONLY",stage:"hold_time",reasons:[`median_hold_${Math.round(medh/60)}m_under_1h`]};const reasons:string[]=[];if(h.closedHolds<3)reasons.push("closed_hold_sample_under_3");if(medh==null)reasons.push("hold_time_unknown");else if(medh<21600)reasons.push("median_hold_under_6h");else if(medh<43200)reasons.push("median_hold_6h_plus");else reasons.push("median_hold_12h_plus");if(vybe.length>=400)reasons.push("high_activity_30d_400plus");if((w.tokens?.length||0)<2)reasons.push("single_discovery_token");else reasons.push(`cross_token_${w.tokens!.length}`);if(errors.length)reasons.push(...errors);if(h.estimatedFollowerTrades>=3&&h.estimatedFollowerNetSol!=null&&h.estimatedFollowerNetSol<=0)return{status:"REJECT",stage:"fixed_size_economics",reasons:[...reasons,"0.075_estimated_net_nonpositive"]};if(medh!=null&&medh>=21600&&h.closedHolds>=3&&(w.tokens?.length||0)>=2&&vybe.length<400&&h.estimatedFollowerNetSol!=null&&h.estimatedFollowerNetSol>0)return{status:"DEEP_DIVE",stage:"pre_replay",reasons:[...reasons,"0.075_source_roi_fee_model_positive","needs_lag_slippage_anti_jackpot_replay"]};return{status:"UNKNOWN",stage:"insufficient_evidence",reasons};}

export async function runGauntlet(){const state=JSON.parse(await fs.readFile(STATE_PATH,"utf8"));const wallets=(Object.values(state.wallets||{}) as Wallet[]).filter(w=>w.status!=="REJECTED").sort((a,b)=>score(b)-score(a)).slice(0,LIMIT),results:any[]=[];for(const w of wallets){const [hx,vt]=await Promise.all([heliusHistory(w.address),vybeTrades(w.address)]),h=holds(hx.rows,w.address),errors:string[]=[];if(hx.error)errors.push("helius_history_partial_or_error");if(vt.error)errors.push("vybe_trade_history_error");const v=verdict(w,h,vt.rows,errors);results.push({address:w.address,discoveryTokens:w.tokens?.length||0,providers:w.providers||[],rediscoveryCount:w.rediscoveryCount||0,heliusTransactions:hx.rows.length,heliusSwaps:hx.rows.filter(x=>x?.type==="SWAP").length,vybeTrades30d:vt.rows.length,hold:h,verdict:v});}
const counts=results.reduce((a:any,x:any)=>(a[x.verdict.status]=(a[x.verdict.status]||0)+1,a),{}),report={schemaVersion:2,generatedAt:new Date().toISOString(),evaluated:results.length,counts,note:"DEEP_DIVE is preliminary. Follower economics normalize source round-trip ROI to 0.075 SOL and subtract Odin 1% fee (0.001 SOL minimum), 0.3% tip per leg and 0.00015 SOL network per leg. It does not yet model historical source-to-copy price displacement, lag, slippage, liquidity impact or jackpot concentration, so it is not LIVE-TEST WORTHY.",results};await fs.mkdir(path.dirname(REPORT_PATH),{recursive:true});await fs.writeFile(REPORT_PATH,JSON.stringify(report,null,2));console.log(JSON.stringify({event:"shark_scout_gauntlet_complete",generatedAt:report.generatedAt,evaluated:results.length,counts,top:results.slice(0,12).map(x=>({address:x.address,status:x.verdict.status,medianHoldSeconds:x.hold.medianHoldSeconds,closedHolds:x.hold.closedHolds,discoveryTokens:x.discoveryTokens,vybeTrades30d:x.vybeTrades30d,estimatedFollowerNetSol:x.hold.estimatedFollowerNetSol,reasons:x.verdict.reasons}))}));return report;}
if(import.meta.url===`file://${process.argv[1]}`)runGauntlet().catch(e=>{console.error(JSON.stringify({event:"shark_scout_gauntlet_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});
