import { promises as fs } from "node:fs";
import path from "node:path";

const HELIUS_KEY=process.env.HELIUS_API_KEY?.trim();
const WALLET=process.env.SCOUT_WALLET_ADDRESS?.trim();
const ODIN_PATH=process.env.SCOUT_ODIN_SNAPSHOT_PATH||"/data/odin-config.json";
const OUT_PATH=process.env.SCOUT_OPPORTUNITY_PATH||"/data/mirror-opportunity-audit.json";
const CACHE_PATH=process.env.SCOUT_OPPORTUNITY_CACHE_PATH||"/data/mirror-opportunity-cache.json";
const POLL_HOURS=clamp(Number(process.env.OPPORTUNITY_POLL_HOURS||6),1,24);
const LIMIT=clamp(Number(process.env.OPPORTUNITY_TX_LIMIT||60),20,100);
const LOOKBACK_HOURS=clamp(Number(process.env.OPPORTUNITY_LOOKBACK_HOURS||24),6,72);
const MATCH_SECONDS=clamp(Number(process.env.OPPORTUNITY_MATCH_SECONDS||900),60,3600);
const FOLLOW_SIZE=.075,ODIN_RATE=.01,TIP_RATE=.003,NETWORK=.00015;
const WSOL="So11111111111111111111111111111111111111112",USDC="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",USDT="Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB";
const QUOTES=new Set([WSOL,USDC,USDT]);
type AnyObj=Record<string,any>;
type Event={wallet:string;signature:string;timestamp:number;side:"BUY"|"SELL";mint:string;qty:number|null;quoteSol:number|null};
function clamp(n:number,min:number,max:number){return Math.max(min,Math.min(max,Number.isFinite(n)?Math.floor(n):min));}
function now(){return new Date().toISOString();}
function num(v:any){const n=Number(v);return Number.isFinite(n)?n:null;}
async function readJson(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomicSave(file:string,data:any){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(data));await fs.rename(tmp,file);}
async function fetchRows(address:string){if(!HELIUS_KEY)return[];const q=new URLSearchParams({"api-key":HELIUS_KEY,limit:String(LIMIT),type:"SWAP"});const c=new AbortController(),t=setTimeout(()=>c.abort(),25000);try{const r=await fetch(`https://api.helius.xyz/v0/addresses/${address}/transactions?${q}`,{signal:c.signal});if(!r.ok)throw new Error(`${r.status}:${(await r.text()).slice(0,120)}`);const x=await r.json();return Array.isArray(x)?x:[];}finally{clearTimeout(t);}}
function nativeSol(x:any){const n=num(x?.amount);return n==null?null:n/1e9;}
function quoteTransfer(tx:any,wallet:string,dir:"out"|"in"){let total=0,seen=false;for(const x of tx?.nativeTransfers||[]){const hit=dir==="out"?x?.fromUserAccount===wallet:x?.toUserAccount===wallet;if(hit){const v=nativeSol(x);if(v!=null){total+=v;seen=true;}}}for(const x of tx?.tokenTransfers||[]){if(x?.mint!==WSOL)continue;const hit=dir==="out"?x?.fromUserAccount===wallet:x?.toUserAccount===wallet;if(hit){const v=num(x?.tokenAmount);if(v!=null){total+=v;seen=true;}}}return seen?total:null;}
function events(rows:any[],wallet:string){const out:Event[]=[];for(const tx of rows){const ts=Number(tx?.timestamp);if(!Number.isFinite(ts))continue;const sw=tx?.events?.swap;let buys:any[]=[],sells:any[]=[];if(sw){buys=(sw.tokenOutputs||[]).filter((x:any)=>x?.userAccount===wallet&&!QUOTES.has(x?.mint));sells=(sw.tokenInputs||[]).filter((x:any)=>x?.userAccount===wallet&&!QUOTES.has(x?.mint));}if(!buys.length&&!sells.length){for(const x of tx?.tokenTransfers||[]){if(!x?.mint||QUOTES.has(x.mint))continue;if(x?.toUserAccount===wallet&&x?.fromUserAccount!==wallet)buys.push(x);if(x?.fromUserAccount===wallet&&x?.toUserAccount!==wallet)sells.push(x);}}
    const buyQ=nativeSol(sw?.nativeInput)??quoteTransfer(tx,wallet,"out"),sellQ=nativeSol(sw?.nativeOutput)??quoteTransfer(tx,wallet,"in");
    if(buys.length===1){const x=buys[0];out.push({wallet,signature:String(tx?.signature||""),timestamp:ts,side:"BUY",mint:String(x?.mint||""),qty:num(x?.tokenAmount??x?.rawTokenAmount?.tokenAmount),quoteSol:buyQ});}
    if(sells.length===1){const x=sells[0];out.push({wallet,signature:String(tx?.signature||""),timestamp:ts,side:"SELL",mint:String(x?.mint||""),qty:num(x?.tokenAmount??x?.rawTokenAmount?.tokenAmount),quoteSol:sellQ});}
  }return out.sort((a,b)=>a.timestamp-b.timestamp);}
function followerNetFromSourceRoi(roi:number){const bf=Math.max(FOLLOW_SIZE*ODIN_RATE,.001),bt=FOLLOW_SIZE*TIP_RATE,cost=FOLLOW_SIZE+bf+bt+NETWORK,gross=Math.max(0,FOLLOW_SIZE*(1+roi)),sf=Math.max(gross*ODIN_RATE,.001),st=gross*TIP_RATE;return gross-sf-st-NETWORK-cost;}
function completedSourceRoundTrip(buy:Event,all:Event[]){if(buy.qty==null||buy.quoteSol==null||buy.qty<=0||buy.quoteSol<=0)return null;let sold=0,proceeds=0;for(const s of all){if(s.timestamp<=buy.timestamp||s.side!=="SELL"||s.mint!==buy.mint||s.qty==null||s.quoteSol==null)continue;const need=Math.max(0,buy.qty-sold);if(need<=0)break;const take=Math.min(need,s.qty),frac=s.qty>0?take/s.qty:0;sold+=take;proceeds+=s.quoteSol*frac;if(sold>=buy.qty*.9)break;}if(sold<buy.qty*.9)return null;const basis=buy.quoteSol*(sold/buy.qty),roi=basis>0?(proceeds-basis)/basis:null;return roi==null?null:{soldFraction:sold/buy.qty,sourceRoi:roi,estimatedFollowerNetSol:followerNetFromSourceRoi(roi)};}
async function main(){const startedAt=now();const cache=await readJson(CACHE_PATH,{});const age=cache?.lastRunAt?Date.now()-Date.parse(cache.lastRunAt):Infinity;if(Number.isFinite(age)&&age<POLL_HOURS*3600_000){console.log(JSON.stringify({event:"shark_scout_opportunity_audit_skipped",startedAt,pollHours:POLL_HOURS,nextDueInMinutes:Math.ceil((POLL_HOURS*3600_000-age)/60000)}));return;}if(!HELIUS_KEY||!WALLET){console.log(JSON.stringify({event:"shark_scout_opportunity_audit_complete",startedAt,enabled:false,errors:[!HELIUS_KEY?"missing_helius_key":"missing_wallet"],finishedAt:now()}));return;}const odin=await readJson(ODIN_PATH,{}),mirrors=(Array.isArray(odin?.mirrors)?odin.mirrors:[]).map((x:any)=>String(x?.address||"")).filter(Boolean);const errors:string[]=[];let followerRows:any[]=[];try{followerRows=await fetchRows(WALLET);}catch(e){errors.push(`follower:${String(e)}`);}const followerEvents=events(followerRows,WALLET);const cutoff=Math.floor(Date.now()/1000)-LOOKBACK_HOURS*3600;const perMirror:any[]=[];let totalOpp=0,totalCopied=0,totalUnknownMiss=0,wouldWin=0,wouldLose=0;
  for(const mirror of mirrors){try{const rows=await fetchRows(mirror),ev=events(rows,mirror),buys=ev.filter(x=>x.side==="BUY"&&x.timestamp>=cutoff);const seenMint=new Set<string>(),ops:any[]=[];for(const b of buys){if(seenMint.has(b.mint))continue;seenMint.add(b.mint);const copy=followerEvents.find(x=>x.side==="BUY"&&x.mint===b.mint&&x.timestamp>=b.timestamp&&x.timestamp-b.timestamp<=MATCH_SECONDS);const rt=completedSourceRoundTrip(b,ev);let cls="NOT_COPIED_REASON_UNKNOWN";if(copy)cls="COPIED";else if(rt?.estimatedFollowerNetSol!=null)cls=rt.estimatedFollowerNetSol>0?"NOT_COPIED_WOULD_HAVE_WON":"NOT_COPIED_WOULD_HAVE_LOST";ops.push({mint:b.mint,sourceBuyAt:new Date(b.timestamp*1000).toISOString(),sourceBuySol:b.quoteSol,sourceBuyQty:b.qty,copied:Boolean(copy),copyDelaySeconds:copy?copy.timestamp-b.timestamp:null,sourceRoundTrip:rt,classification:cls});totalOpp++;if(copy)totalCopied++;else{totalUnknownMiss++;if(cls.endsWith("WON"))wouldWin++;if(cls.endsWith("LOST"))wouldLose++;}}perMirror.push({mirror,opportunityCount:ops.length,copiedCount:ops.filter(x=>x.copied).length,notCopiedCount:ops.filter(x=>!x.copied).length,opportunityDetails:ops.slice(-30)});}catch(e){errors.push(`${mirror}:${String(e)}`);}}
  const out={schemaVersion:1,event:"shark_scout_opportunity_audit_complete",startedAt,finishedAt:now(),pollHours:POLL_HOURS,lookbackHours:LOOKBACK_HOURS,mirrorCount:mirrors.length,totalOpportunities:totalOpp,copied:totalCopied,eligibleOpportunityRate:totalOpp?totalCopied/totalOpp:null,notCopiedReasonUnknown:totalUnknownMiss,counterfactualWouldHaveWon:wouldWin,counterfactualWouldHaveLost:wouldLose,perMirror,errors,warning:"A not-copied event is not assigned a filter reason because Odin trade-history/skip reasons are unavailable from the checked API. Counterfactual outcome is estimated only when a source round trip is reconstructable."};await atomicSave(OUT_PATH,out);await atomicSave(CACHE_PATH,{lastRunAt:out.finishedAt});console.log(JSON.stringify(out));}
main().catch(e=>{console.error(JSON.stringify({event:"shark_scout_opportunity_audit_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});
