import { promises as fs } from "node:fs";
import path from "node:path";

const ACTUAL_PATH=process.env.SCOUT_ODIN_ACTUAL_RECONCILIATION_PATH||"/data/odin-actual-reconciliation.json";
const LADDER_PATH=process.env.SCOUT_REPLACEMENT_LADDER_PATH||"/data/replacement-ladder.json";
const FUNNEL_PATH=process.env.SCOUT_EVIDENCE_FUNNEL_PATH||"/data/evidence-funnel.json";
const QUOTA_PATH=process.env.SCOUT_QUOTA_SHIELD_PATH||"/data/quota-shield-summary.json";
const ODIN_PATH=process.env.SCOUT_ODIN_SNAPSHOT_PATH||"/data/odin-config.json";
const OUT_PATH=process.env.SCOUT_MISSION_REPORT_PATH||"/data/mission-report.json";

async function read(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomic(file:string,data:any){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(data,null,2));await fs.rename(tmp,file);}
export async function buildMissionReport(){const generatedAt=new Date().toISOString();const [actual,ladder,funnel,quota,odin]=await Promise.all([read(ACTUAL_PATH,{}),read(LADDER_PATH,{}),read(FUNNEL_PATH,{}),read(QUOTA_PATH,{}),read(ODIN_PATH,{})]);const replacements=Array.isArray(ladder?.replacementCandidates)?ladder.replacementCandidates:[];const liveMirrors=(Array.isArray(odin?.mirrors)?odin.mirrors:[]).map((x:any)=>({address:String(x?.address||""),allowBuys:x?.allowBuys??null,maxBuysPerMirrorPerDay:x?.maxBuysPerMirrorPerDay??null,tradeSizeLamports:x?.tradeSizeLamports??null,minMarketCap:x?.minMarketCap??x?.minMarketCapUsd??null,maxMarketCap:x?.maxMarketCap??x?.maxMarketCapUsd??null,onlyCopyNewPositions:x?.onlyCopyNewPositions??null})).filter((x:any)=>x.address);const out={schemaVersion:1,event:"shark_scout_mission_report_complete",generatedAt,mission:{primary:"Find Odin-copyable wallets with positive transferred expectancy and continuously replace weaker mirrors.",priorityOrder:["ACTUAL_ODIN truth","prospective Odin transferability","canonical replay robustness","discovery breadth"]},actualOdin:{governanceSafe:Boolean(actual?.summary?.governanceSafe),summary:actual?.summary||{},byMirror:actual?.byMirror||[],unattributedClosed:(actual?.rows||[]).filter((x:any)=>x?.closed&&!x?.mirror)},replacement:{gods:ladder?.tiers?.GOD||[],trialReady:ladder?.tiers?.TRIAL_READY||[],topCandidates:replacements.slice(0,5),changes:ladder?.changes||[],noReplacementEarned:replacements.length===0},discovery:{evaluated:funnel?.evaluated??null,actionableCount:funnel?.actionableCount??null,canonicalCoverage:funnel?.canonicalCoverage??null,topNearPasses:funnel?.topNearPasses?.slice?.(0,5)||[]},provider:{health:quota?.semanticHealth||"UNKNOWN",pressure:quota?.quotaPressure||{}},odinSnapshot:{fetchedAt:odin?.fetchedAt||null,changedSincePrevious:odin?.changedSincePrevious??null,mirrors:liveMirrors},guardrails:{advisoryOnly:true,autoOdinMutation:false,note:"Odin changes require a specific evidence-backed action; this report never mutates trading settings."}};await atomic(OUT_PATH,out);console.log(JSON.stringify(out));return out;}
if(import.meta.url===`file://${process.argv[1]}`)buildMissionReport().catch(e=>{console.error(JSON.stringify({event:"shark_scout_mission_report_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});