import { promises as fs } from "node:fs";
import path from "node:path";
import { metrics, type Layer, type TradeResult } from "./ab_metrics.js";
import { sha256, stableJson } from "./prospective_ab_lab.js";
import { fetchNormalizedHistory } from "./transaction_fabric.js";

const OPPORTUNITY_PATH=process.env.SCOUT_OPPORTUNITY_PATH||"/data/mirror-opportunity-audit.json";
const TRUTH_PATH=process.env.SCOUT_ODIN_TRUTH_LEDGER_PATH||"/data/odin-truth-ledger.json";
const PORTFOLIO_CACHE_PATH=process.env.SCOUT_PORTFOLIO_HISTORY_CACHE||"/data/portfolio-history-cache.json";
const ODIN_PATH=process.env.SCOUT_ODIN_SNAPSHOT_PATH||"/data/odin-config.json";
const FUNNEL_PATH=process.env.SCOUT_EVIDENCE_FUNNEL_PATH||"/data/evidence-funnel.json";
const STATE_PATH=process.env.SCOUT_ODIN_TRANSFER_STATE_PATH||"/data/odin-transfer-state.json";
const OUT_PATH=process.env.SCOUT_ODIN_TRANSFER_REPORT_PATH||"/data/odin-transfer-report.json";
const RESULTS_PATH=process.env.SCOUT_EXPERIMENT_RESULTS_PATH||"/data/prospective-ab/experiment-results.jsonl";
const FOLLOWER_WALLET=(process.env.SCOUT_WALLET_ADDRESS||process.env.SHARK_FOLLOWER_WALLET||"").trim();
const FOLLOWER_REFRESH_PAGES=Math.max(1,Math.min(8,Number(process.env.ODIN_TRANSFER_FOLLOWER_REFRESH_PAGES||4)));
const NORMALIZED_SOURCE_SIZE=Math.max(.01,Math.min(1,Number(process.env.ODIN_TRANSFER_SOURCE_SIZE_SOL||.075)));
const MAX_ROWS=Math.max(500,Math.min(20000,Number(process.env.ODIN_TRANSFER_MAX_ROWS||8000)));
const ACTUAL_CLOSE_FRACTION=Math.max(.90,Math.min(.9999,Number(process.env.ODIN_TRANSFER_CLOSE_FRACTION||.995)));

type AnyObj=Record<string,any>;
type FollowerEvent={signature:string;ts:number|null;mint:string;side:"BUY"|"SELL";qty:number;sol:number;confidence?:string;quote?:string};
type State={schemaVersion:number;rows:Record<string,TradeResult>;updatedAt?:string};
type ExecutionDiagnostic={wallet:string;opportunityId:string;mint:string;copySignature:string;sourceBuyTs:number|null;followerBuyTs:number;sourceExitTs:number|null;followerExitTs:number|null;buyLatencySec:number|null;exitLatencySec:number|null;perfectCopyNetSol:number;actualNetSol:number|null;executionGapSol:number|null;executionRetention:number|null;closed:boolean;closedFraction:number};

function now(){return new Date().toISOString();}
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:null;}
function clamp01(v:number){return Math.max(0,Math.min(1,v));}
function sec(v:any){const x=n(v);if(x!=null&&x>0)return x>1e12?x/1000:x;const p=Date.parse(String(v||""));return Number.isFinite(p)?p/1000:null;}
function median(xs:number[]){if(!xs.length)return null;const a=[...xs].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]!:(a[m-1]!+a[m]!)/2;}
function percentile(xs:number[],p:number){if(!xs.length)return null;const a=[...xs].sort((x,y)=>x-y),i=Math.max(0,Math.min(a.length-1,Math.ceil(p*a.length)-1));return a[i]!;}
async function read(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomic(file:string,data:string){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,data);await fs.rename(tmp,file);}
function resultId(wallet:string,opportunityId:string,layer:Layer){return sha256(`${wallet}|${opportunityId}|${layer}`);}
function addRow(state:State,row:TradeResult){state.rows[row.tradeId]=row;}
function sourceResolvedAt(x:any){const ts=n(x?.sourceRoundTrip?.finalSellTimestamp);return ts&&ts>0?new Date(ts*1000).toISOString():String(x?.sourceBuyAt||now());}
function truthMap(truth:any){return new Map(Object.values(truth?.entries||{}).map((x:any)=>[String(x?.opportunityId||""),x]));}

function eventFromNormalized(tx:any):FollowerEvent|null{
  const ts=n(tx?.timestamp),sig=String(tx?.signature||"");if(!sig||ts==null)return null;const sw=tx?.events?.swap;const buys=Array.isArray(sw?.tokenOutputs)?sw.tokenOutputs:[],sells=Array.isArray(sw?.tokenInputs)?sw.tokenInputs:[];
  if(buys.length===1){const q=n(buys[0]?.tokenAmount),sol=n(sw?.nativeInput?.amount);if(q!=null&&q>0&&sol!=null&&sol>=0)return{signature:sig,ts,mint:String(buys[0]?.mint||""),side:"BUY",qty:q,sol:sol/1e9,confidence:"HIGH",quote:"NATIVE_SOL"};}
  if(sells.length===1){const q=n(sells[0]?.tokenAmount),sol=n(sw?.nativeOutput?.amount);if(q!=null&&q>0&&sol!=null&&sol>=0)return{signature:sig,ts,mint:String(sells[0]?.mint||""),side:"SELL",qty:q,sol:sol/1e9,confidence:"HIGH",quote:"NATIVE_SOL"};}
  return null;
}

async function refreshFollowerCache(){
  const status:any={attempted:Boolean(FOLLOWER_WALLET),walletConfigured:Boolean(FOLLOWER_WALLET),source:"provider_fabric_raw",newEvents:0,pagesFetched:0,providerCalls:0,cacheHits:0,error:null};if(!FOLLOWER_WALLET)return status;
  try{const cache=await read(PORTFOLIO_CACHE_PATH,{schemaVersion:2,events:{},movements:{},seen:{}});cache.schemaVersion=2;cache.events=cache.events||{};cache.movements=cache.movements||{};cache.seen=cache.seen||{};const stop=String(cache?.attributionCursor?.newestSignature||"")||null;const got=await fetchNormalizedHistory({address:FOLLOWER_WALLET,stopSignature:stop,pageLimit:100,maxPages:stop?FOLLOWER_REFRESH_PAGES:2});for(const row of got.rows){const e=eventFromNormalized(row);if(!e||!e.mint)continue;if(!cache.events[e.signature])status.newEvents++;cache.events[e.signature]=e;cache.seen[e.signature]=1;}cache.attributionCursor={newestSignature:got.newestSignature||stop,lastCheckedAt:now(),pagesFetched:got.pagesFetched,reachedPriorCursor:stop?got.reachedStop:true,gapDetected:Boolean(stop&&got.truncated&&!got.reachedStop),source:got.source};await atomic(PORTFOLIO_CACHE_PATH,JSON.stringify(cache));status.pagesFetched=got.pagesFetched;status.providerCalls=got.providerCalls;status.cacheHits=got.cacheHits;status.gapDetected=cache.attributionCursor.gapDetected;return status;}catch(e){status.error=e instanceof Error?e.message:String(e);return status;}
}

function followerLots(cache:any){
  const events=(Object.values(cache?.events||{}) as FollowerEvent[]).filter(e=>e&&e.signature&&e.mint&&e.qty>0&&e.sol>=0&&e.ts!=null).sort((a,b)=>Number(a.ts)-Number(b.ts));
  type Lot={signature:string;mint:string;ts:number;qtyInitial:number;qtyRemaining:number;costSol:number;proceedsSol:number;soldQty:number;resolvedAt:string|null};
  const open=new Map<string,Lot[]>(),all=new Map<string,Lot>();
  for(const e of events){if(e.side==="BUY"){const lot:Lot={signature:e.signature,mint:e.mint,ts:Number(e.ts),qtyInitial:e.qty,qtyRemaining:e.qty,costSol:e.sol,proceedsSol:0,soldQty:0,resolvedAt:null};const q=open.get(e.mint)||[];q.push(lot);open.set(e.mint,q);all.set(lot.signature,lot);continue;}let remain=e.qty;const q=open.get(e.mint)||[];while(remain>1e-12&&q.length){const lot=q[0]!,take=Math.min(remain,lot.qtyRemaining),frac=e.qty>0?take/e.qty:0;lot.qtyRemaining-=take;lot.soldQty+=take;lot.proceedsSol+=e.sol*frac;remain-=take;if(lot.qtyRemaining<=lot.qtyInitial*(1-ACTUAL_CLOSE_FRACTION)){lot.resolvedAt=new Date(Number(e.ts)*1000).toISOString();q.shift();}else if(take<=1e-12)break;}open.set(e.mint,q);}return all;
}
function cohortSets(odin:any,funnel:any){const live=new Set((Array.isArray(odin?.mirrors)?odin.mirrors:[]).map((x:any)=>String(x?.address||"")).filter(Boolean));const research=new Set((Array.isArray(funnel?.topActionable)?funnel.topActionable:[]).map((x:any)=>String(x?.address||"")).filter((x:string)=>x&&!live.has(x)));const controls=new Set((Array.isArray(funnel?.topNearPasses)?funnel.topNearPasses:[]).map((x:any)=>String(x?.address||"")).filter((x:string)=>x&&!live.has(x)&&!research.has(x)));return{live,research,controls};}
function timingFor(diags:ExecutionDiagnostic[],wallet:string){const x=diags.filter(d=>d.wallet===wallet),buys=x.map(d=>d.buyLatencySec).filter((v):v is number=>v!=null&&v>=0),exits=x.map(d=>d.exitLatencySec).filter((v):v is number=>v!=null&&v>=0),gaps=x.map(d=>d.executionGapSol).filter((v):v is number=>v!=null),ret=x.map(d=>d.executionRetention).filter((v):v is number=>v!=null);return{matchedBuys:x.length,closedActual:x.filter(d=>d.closed).length,buyLatencySec:{n:buys.length,median:median(buys),p95:percentile(buys,.95),max:buys.length?Math.max(...buys):null},exitLatencySec:{n:exits.length,median:median(exits),p95:percentile(exits,.95),max:exits.length?Math.max(...exits):null},executionGapSol:{n:gaps.length,median:median(gaps),total:gaps.length?gaps.reduce((a,b)=>a+b,0):null},executionRetention:{n:ret.length,median:median(ret)}};}
function otsFor(rows:TradeResult[],wallet:string,live:boolean){const perfect=rows.filter(x=>x.wallet===wallet&&x.layer==="PERFECT_COPY"),sim=rows.filter(x=>x.wallet===wallet&&x.layer==="SIMULATED_ODIN"),actual=rows.filter(x=>x.wallet===wallet&&x.layer==="ACTUAL_ODIN");const pm=metrics(perfect),sm=metrics(sim),am=metrics(actual),eligibilityCapture=perfect.length?sim.length/perfect.length:null,actualCapture=sim.length?actual.length/sim.length:null;const robustness=sm.netSol>0?clamp01(sm.stress50/sm.netSol):sm.stress50>0?1:0,expectancy=sm.n?clamp01(.5+sm.medianTrade/.075):0,transfer=sm.netSol>0&&am.n?clamp01(am.netSol/sm.netSol):live?0:1,capture=eligibilityCapture==null?0:clamp01(eligibilityCapture),landing=live?(actualCapture==null?0:clamp01(actualCapture)):1,sample=clamp01((live?am.n:sm.n)/20),components=[Math.max(.01,capture),Math.max(.01,robustness),Math.max(.01,expectancy),Math.max(.01,transfer),Math.max(.01,landing)],geometric=Math.pow(components.reduce((a,b)=>a*b,1),1/components.length);return{score:Math.round(100*geometric*(.35+.65*sample)),sampleAdequacy:sample,eligibilityCapture,actualCapture,perfect:pm,simulated:sm,actual:am,components:{capture,robustness,expectancy,executionTransfer:transfer,landingCapture:landing}};}

async function main(){
  const startedAt=now(),followerRefresh=await refreshFollowerCache();
  const [op,truth,portfolio,odin,funnel,state0]=await Promise.all([read(OPPORTUNITY_PATH,{}),read(TRUTH_PATH,{entries:{}}),read(PORTFOLIO_CACHE_PATH,{events:{}}),read(ODIN_PATH,{}),read(FUNNEL_PATH,{}),read(STATE_PATH,{schemaVersion:1,rows:{}})]);
  const state:State={schemaVersion:1,rows:state0?.rows&&typeof state0.rows==="object"?state0.rows:{}};const tmap=truthMap(truth),lots=followerLots(portfolio),diagnostics:ExecutionDiagnostic[]=[],liveAttributions:any[]=[];let opportunities=0,sourceResolved=0,simulatedResolved=0,actualResolved=0,matchedCopyBuys=0;
  for(const mirror of Array.isArray(op?.perMirror)?op.perMirror:[]){const wallet=String(mirror?.mirror||"");if(!wallet)continue;for(const x of Array.isArray(mirror?.opportunityDetails)?mirror.opportunityDetails:[]){const opportunityId=String(x?.opportunityId||"");if(!opportunityId)continue;opportunities++;const tv=tmap.get(opportunityId) as AnyObj|undefined,copySig=String(x?.copySignature||tv?.copySignature||""),lot=copySig?lots.get(copySig):undefined,sourceBuyTs=sec(x?.sourceBuyAt)??sec(x?.sourceTimestamp),rt=x?.sourceRoundTrip,sourceExitTs=sec(rt?.finalSellTimestamp);if(lot){liveAttributions.push({wallet,opportunityId,mint:String(x?.mint||lot.mint),sourceBuySignature:String(x?.sourceSignature||""),sourceBuyTs,copySignature:copySig,followerBuyTs:lot.ts,buyLatencySec:sourceBuyTs==null?null:lot.ts-sourceBuyTs,closedFraction:lot.qtyInitial>0?Math.min(1,lot.soldQty/lot.qtyInitial):0,status:lot.resolvedAt?"CLOSED":"OPEN",sourceResolved:Boolean(rt?.sourceRoi!=null)});}const roi=n(rt?.sourceRoi),perfectNet=n(rt?.estimatedFollowerNetSol);if(roi==null||perfectNet==null)continue;const eligibleAt=String(x?.sourceBuyAt||new Date(Number(x?.sourceTimestamp||0)*1000).toISOString()),resolvedAt=sourceResolvedAt(x);addRow(state,{tradeId:resultId(wallet,opportunityId,"SOURCE"),wallet,layer:"SOURCE",netSol:NORMALIZED_SOURCE_SIZE*roi,eligibleAt,resolvedAt,topWinnerKey:String(x?.mint||opportunityId)});addRow(state,{tradeId:resultId(wallet,opportunityId,"PERFECT_COPY"),wallet,layer:"PERFECT_COPY",netSol:perfectNet,eligibleAt,resolvedAt,topWinnerKey:String(x?.mint||opportunityId)});sourceResolved++;if(tv?.odinEligibility==="ODIN_ELIGIBLE"){addRow(state,{tradeId:resultId(wallet,opportunityId,"SIMULATED_ODIN"),wallet,layer:"SIMULATED_ODIN",netSol:perfectNet,eligibleAt,resolvedAt,topWinnerKey:String(x?.mint||opportunityId)});simulatedResolved++;}if(lot){matchedCopyBuys++;const closed=lot.qtyInitial>0&&lot.soldQty>=lot.qtyInitial*ACTUAL_CLOSE_FRACTION&&!!lot.resolvedAt,actualNet=closed?lot.proceedsSol-lot.costSol:null,followerExitTs=lot.resolvedAt?sec(lot.resolvedAt):null,closedFraction=lot.qtyInitial>0?Math.min(1,lot.soldQty/lot.qtyInitial):0;diagnostics.push({wallet,opportunityId,mint:String(x?.mint||lot.mint),copySignature:copySig,sourceBuyTs,followerBuyTs:lot.ts,sourceExitTs,followerExitTs,buyLatencySec:sourceBuyTs==null?null:lot.ts-sourceBuyTs,exitLatencySec:sourceExitTs==null||followerExitTs==null?null:followerExitTs-sourceExitTs,perfectCopyNetSol:perfectNet,actualNetSol:actualNet,executionGapSol:actualNet==null?null:actualNet-perfectNet,executionRetention:actualNet==null||perfectNet===0?null:actualNet/perfectNet,closed,closedFraction});if(closed&&actualNet!=null){addRow(state,{tradeId:resultId(wallet,opportunityId,"ACTUAL_ODIN"),wallet,layer:"ACTUAL_ODIN",netSol:actualNet,eligibleAt,resolvedAt:lot.resolvedAt!,topWinnerKey:String(x?.mint||opportunityId)});actualResolved++;}}}}
  let rows=Object.values(state.rows).sort((a,b)=>String(a.resolvedAt).localeCompare(String(b.resolvedAt))||a.tradeId.localeCompare(b.tradeId));if(rows.length>MAX_ROWS){rows=rows.slice(-MAX_ROWS);state.rows=Object.fromEntries(rows.map(x=>[x.tradeId,x]));}state.updatedAt=now();await atomic(STATE_PATH,JSON.stringify(state));await atomic(RESULTS_PATH,rows.map(x=>JSON.stringify(x)).join("\n")+(rows.length?"\n":""));
  const cohorts=cohortSets(odin,funnel),wallets=[...new Set([...rows.map(x=>x.wallet),...liveAttributions.map(x=>x.wallet)])].sort(),perWallet=wallets.map(wallet=>({wallet,role:cohorts.live.has(wallet)?"LIVE":cohorts.research.has(wallet)?"RESEARCH":cohorts.controls.has(wallet)?"CONTROL":"OBSERVED",ots:otsFor(rows,wallet,cohorts.live.has(wallet)),execution:timingFor(diagnostics,wallet),liveAttributions:liveAttributions.filter(x=>x.wallet===wallet).slice(-25)})).sort((a,b)=>b.ots.score-a.ots.score),layerTotals=Object.fromEntries((["SOURCE","PERFECT_COPY","SIMULATED_ODIN","ACTUAL_ODIN"] as Layer[]).map(layer=>[layer,metrics(rows.filter(x=>x.layer===layer))])),allBuys=diagnostics.map(d=>d.buyLatencySec).filter((v):v is number=>v!=null&&v>=0),allExits=diagnostics.map(d=>d.exitLatencySec).filter((v):v is number=>v!=null&&v>=0),allGaps=diagnostics.map(d=>d.executionGapSol).filter((v):v is number=>v!=null),executionSummary={matchedCopyBuys,closedActual:diagnostics.filter(d=>d.closed).length,actualCloseFraction:ACTUAL_CLOSE_FRACTION,buyLatencySec:{n:allBuys.length,median:median(allBuys),p95:percentile(allBuys,.95),max:allBuys.length?Math.max(...allBuys):null},exitLatencySec:{n:allExits.length,median:median(allExits),p95:percentile(allExits,.95),max:allExits.length?Math.max(...allExits):null},executionGapSol:{n:allGaps.length,total:allGaps.length?allGaps.reduce((a,b)=>a+b,0):null,median:median(allGaps)}};
  const report={schemaVersion:4,event:followerRefresh.error?"shark_scout_odin_transfer_lab_degraded":"shark_scout_odin_transfer_lab_complete",status:followerRefresh.error?"DEGRADED":"HEALTHY",startedAt,finishedAt:now(),followerRefresh,opportunities,sourceResolved,simulatedResolved,matchedCopyBuys,actualResolved,liveAttributionCount:liveAttributions.length,openAttributed:liveAttributions.filter(x=>x.status==="OPEN").length,totalTradeRows:rows.length,cohorts:{live:[...cohorts.live].sort(),research:[...cohorts.research].sort(),controls:[...cohorts.controls].sort()},layerTotals,executionSummary,perWallet,liveAttributions:liveAttributions.slice(-100),executionDiagnostics:diagnostics,methodology:{source:"Source ROI normalized to configured source-size SOL.",perfectCopy:"Source round-trip replayed at Odin-sized economics from opportunity audit.",simulatedOdin:"Perfect-copy result included only when Paper Odin classified the source opportunity ODIN_ELIGIBLE.",actualOdin:`Follower wallet FIFO lot reconstructed from exact matched copy signature and provider-neutral on-chain balance deltas; emitted only after >=${(ACTUAL_CLOSE_FRACTION*100).toFixed(1)}% of that exact lot is sold.`,liveAttribution:"Open and closed source-to-follower matches are surfaced even before source round-trip resolution; this is attribution evidence, not realized P&L.",latency:"Buy latency is source-buy timestamp to matched follower-buy timestamp; exit latency is source final-sell timestamp to follower lot closure.",executionGap:"ACTUAL_ODIN net SOL minus PERFECT_COPY net SOL for the same exact matched opportunity.",ots:"Sample-adjusted geometric transferability score. Advisory research ranking only; never mutates Odin."},guardrails:{advisoryOnly:true,odinMutation:false,capitalMutation:false,mirrorMutation:false},hash:sha256(stableJson(rows))};await atomic(OUT_PATH,JSON.stringify(report));console.log(JSON.stringify(report));
}
main().catch(e=>{console.error(JSON.stringify({event:"shark_scout_odin_transfer_lab_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});
