import { promises as fs } from "node:fs";
import path from "node:path";
import { tradeLevelFragility } from "./odin_fragility_math.js";

const FUNNEL=process.env.SCOUT_EVIDENCE_FUNNEL_PATH||"/data/evidence-funnel.json";
const WALK=process.env.SCOUT_WALKFORWARD_STATE_PATH||"/data/prospective-walkforward.json";
const GAUNTLET=process.env.SCOUT_GAUNTLET_STATE_PATH||"/data/gauntlet-state.json";
const OUT=process.env.SCOUT_POLICY_FRAGILITY_PATH||"/data/odin-policy-fragility.json";
const TOP=Math.max(3,Math.min(20,Number(process.env.POLICY_FRAGILITY_TOP||10)));
const now=()=>new Date().toISOString();
async function read(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomic(file:string,data:any){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(data));await fs.rename(tmp,file);}
function finite(v:any){const n=Number(v);return Number.isFinite(n)?n:null;}
function candidateRows(f:any){const seen=new Set<string>(),out:any[]=[];for(const bucket of [f?.topActionable,f?.topNearPasses,f?.topReplayBlocks,f?.topSampleQualityBlocks])for(const x of Array.isArray(bucket)?bucket:[]){const a=String(x?.address||"");if(a&&!seen.has(a)){seen.add(a);out.push(x);}}return out.slice(0,TOP);}
function summaryFragility(x:any){const r=x?.replay||{},net=finite(r.net),stress=finite(r.stress50),trades=finite(r.trades),win=finite(r.winRate),pf=finite(r.profitFactor),largest=finite(r.largestWinnerShare??r.topWinnerShare);const stressRetention=net!=null&&net>0&&stress!=null?stress/net:null;const sample=Math.min(1,(trades??0)/50);let score=0;score+=sample*25;if(stressRetention!=null)score+=Math.max(0,Math.min(1,stressRetention))*30;if(pf!=null)score+=Math.max(0,Math.min(1,(pf-1)/2))*20;if(win!=null)score+=Math.max(0,Math.min(1,win))*10;if(largest!=null)score+=Math.max(0,1-Math.min(1,largest))*15;else score+=7.5;const flags:string[]=[];if((trades??0)<20)flags.push("LOW_SAMPLE");if(stress!=null&&stress<=0)flags.push("STRESS50_NEGATIVE");if(stressRetention!=null&&stressRetention<.25)flags.push("LOW_STRESS_RETENTION");if(pf!=null&&pf<1.15)flags.push("LOW_PROFIT_FACTOR");if(largest!=null&&largest>.5)flags.push("TOP_WINNER_DEPENDENCE");return{score:Math.round(score),flags,metrics:{trades,netSol:net,stress50Sol:stress,stressRetention,profitFactor:pf,winRate:win,largestWinnerShare:largest}};}
function policyGrid(x:any){const mc=[100000,250000,500000,750000,1000000],caps=[1,2,3],ages=[0,60,300,1800],dips=[0,3,5,10];const current=finite(x?.replay?.net),stress=finite(x?.replay?.stress50);return{marketCapFloorsUsd:mc,dailyCaps:caps,minTokenAgeSeconds:ages,buyDipPercent:dips,totalCells:mc.length*caps.length*ages.length*dips.length,status:"SHADOW_ONLY",baseline:{netSol:current,stress50Sol:stress},rule:"A setting is robust only if a contiguous neighborhood remains positive out-of-sample; never promote the single best historical cell."};}
function deepFlags(d:any){const flags:string[]=[];if(!d||!d.trades)return ["NO_TRADE_LEVEL_SERIES"];if(d.trades<20)flags.push("LOW_SAMPLE");if(d.netExLargestWinnerSol<=0)flags.push("FAILS_EX_LARGEST_WINNER");if(d.netExTop3Sol<=0)flags.push("FAILS_EX_TOP3");if(d.netExTop5PctSol<=0)flags.push("FAILS_EX_TOP5PCT");if(d.bootstrapProbabilityPositiveExpectancy!=null&&d.bootstrapProbabilityPositiveExpectancy<.8)flags.push("LOW_BOOTSTRAP_CONFIDENCE");if(d.positiveRegimeShare!=null&&d.positiveRegimeShare<2/3)flags.push("REGIME_INSTABILITY");if(d.profitableTokenShare!=null&&d.profitableTokenShare<.5)flags.push("TOKEN_CONCENTRATION");if(d.rolling10?.positiveShare!=null&&d.rolling10.positiveShare<.6)flags.push("ROLLING10_WEAK");return flags;}
async function main(){const startedAt=now(),[f,w,g]=await Promise.all([read(FUNNEL,{}),read(WALK,{cohorts:[]}),read(GAUNTLET,{results:{}})]);const rows=candidateRows(f).map((x:any)=>{const address=String(x.address),trips=Array.isArray(g?.results?.[address]?.canonicalReplay?.roundTrips)?g.results[address].canonicalReplay.roundTrips:[],deep=tradeLevelFragility(address,trips);return{address,actionable:Boolean(x.actionable),canonicalOverlayStatus:x?.canonicalOverlayStatus??null,nearPassScore:finite(x?.nearPassScore),fragility:summaryFragility(x),tradeLevelFragility:deep,tradeLevelFlags:deepFlags(deep),policyResearch:policyGrid(x)};});const cohorts=Array.isArray(w?.cohorts)?w.cohorts:[],latest=cohorts[cohorts.length-1]||null;const out={schemaVersion:2,event:"shark_scout_policy_fragility_complete",startedAt,finishedAt:now(),candidateCount:rows.length,latestProspectiveCohort:latest?{cohortId:latest.cohortId,frozenAt:latest.frozenAt,members:Array.isArray(latest.members)?latest.members.length:0}:null,candidates:rows,guardrails:{shadowOnly:true,odinMutation:false,capitalMutation:false,latencyOptimization:false,newProviderCalls:0},notes:["This stage consumes persisted Scout evidence only; it performs zero provider/API calls.","Trade-level fragility is calculated from canonical trusted round trips persisted by Replay Core.","Robustness checks remove the largest winner, top 3 winners, and top 5% of trades; calculate median trade, profit factor, downside deviation, max drawdown, rolling 10/20-trade expectancy, deterministic bootstrap probability of positive expectancy, token breadth, and chronological regime stability.","The grid defines counterfactual research cells. It does not claim historical performance for cells that have not yet accumulated prospective observations.","The policy matrix remains shadow-only. No live Odin controls are changed by this stage."]};await atomic(OUT,out);console.log(JSON.stringify(out));}
main().catch(e=>{console.error(JSON.stringify({event:"shark_scout_policy_fragility_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});
