import { promises as fs } from "node:fs";
import path from "node:path";

const PORTFOLIO_PATH=process.env.SCOUT_PORTFOLIO_HISTORY_CACHE||"/data/portfolio-history-cache.json";
const OPPORTUNITY_PATH=process.env.SCOUT_OPPORTUNITY_PATH||"/data/mirror-opportunity-audit.json";
const TRUTH_PATH=process.env.SCOUT_ODIN_TRUTH_LEDGER_PATH||"/data/odin-truth-ledger.json";
const FOLLOWER_PATH=process.env.SCOUT_FOLLOWER_POLICY_LEDGER_PATH||"/data/follower-policy-ledger.json";
const OUT_PATH=process.env.SCOUT_ODIN_ACTUAL_RECONCILIATION_PATH||"/data/odin-actual-reconciliation.json";
const MATCH_WINDOW_SEC=Math.max(60,Math.min(3600,Number(process.env.ODIN_ACTUAL_MATCH_WINDOW_SEC||1800)));
const CLOSE_FRACTION=Math.max(.90,Math.min(.9999,Number(process.env.ODIN_TRANSFER_CLOSE_FRACTION||.995)));

type AnyObj=Record<string,any>;
type Event={signature:string;ts:number;mint:string;side:"BUY"|"SELL";qty:number;sol:number};
type Lot={signature:string;mint:string;ts:number;qtyInitial:number;qtyRemaining:number;costSol:number;proceedsSol:number;soldQty:number;resolvedAt:string|null};
type Candidate={mirror:string;opportunityId:string|null;sourceSignature:string|null;mint:string;sourceTs:number|null;copySignature:string|null};

async function read(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomic(file:string,data:any){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(data,null,2));await fs.rename(tmp,file);}
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:null;}
function sec(v:any){const x=n(v);if(x!=null&&x>0)return x>1e12?x/1000:x;const p=Date.parse(String(v||""));return Number.isFinite(p)?p/1000:null;}
function eventsFromCache(cache:any):Event[]{return (Object.values(cache?.events||{}) as AnyObj[]).map(x=>({signature:String(x?.signature||""),ts:Number(x?.ts??x?.timestamp),mint:String(x?.mint||""),side:String(x?.side||"").toUpperCase() as "BUY"|"SELL",qty:Number(x?.qty),sol:Number(x?.sol)})).filter(x=>x.signature&&x.mint&&Number.isFinite(x.ts)&&x.ts>0&&(x.side==="BUY"||x.side==="SELL")&&Number.isFinite(x.qty)&&x.qty>0&&Number.isFinite(x.sol)&&x.sol>=0).sort((a,b)=>a.ts-b.ts);}
function buildLots(events:Event[]){const open=new Map<string,Lot[]>(),all:Lot[]=[];for(const e of events){if(e.side==="BUY"){const lot:Lot={signature:e.signature,mint:e.mint,ts:e.ts,qtyInitial:e.qty,qtyRemaining:e.qty,costSol:e.sol,proceedsSol:0,soldQty:0,resolvedAt:null};const q=open.get(e.mint)||[];q.push(lot);open.set(e.mint,q);all.push(lot);continue;}let remain=e.qty;const q=open.get(e.mint)||[];while(remain>1e-12&&q.length){const lot=q[0]!,take=Math.min(remain,lot.qtyRemaining),frac=e.qty>0?take/e.qty:0;lot.qtyRemaining-=take;lot.soldQty+=take;lot.proceedsSol+=e.sol*frac;remain-=take;if(lot.qtyRemaining<=lot.qtyInitial*(1-CLOSE_FRACTION)){lot.resolvedAt=new Date(e.ts*1000).toISOString();q.shift();}else if(take<=1e-12)break;}open.set(e.mint,q);}return all;}
function candidates(op:any,truth:any,follower:any){const out:Candidate[]=[];const seen=new Set<string>();const add=(x:Candidate)=>{const key=`${x.mirror}|${x.opportunityId||""}|${x.sourceSignature||""}|${x.copySignature||""}`;if(!x.mirror||!x.mint||seen.has(key))return;seen.add(key);out.push(x);};for(const m of Array.isArray(op?.perMirror)?op.perMirror:[]){const mirror=String(m?.mirror||"");for(const x of Array.isArray(m?.opportunityDetails)?m.opportunityDetails:[])add({mirror,opportunityId:String(x?.opportunityId||"")||null,sourceSignature:String(x?.sourceSignature||"")||null,mint:String(x?.mint||""),sourceTs:sec(x?.sourceBuyAt)??sec(x?.sourceTimestamp),copySignature:String(x?.copySignature||"")||null});}for(const x of Object.values(truth?.entries||{}) as AnyObj[])add({mirror:String(x?.mirror||""),opportunityId:String(x?.opportunityId||"")||null,sourceSignature:String(x?.sourceSignature||"")||null,mint:String(x?.mint||""),sourceTs:sec(x?.sourceBuyAt)??sec(x?.sourceTimestamp),copySignature:String(x?.copySignature||"")||null});for(const x of Object.values(follower?.entries||{}) as AnyObj[])add({mirror:String(x?.mirror||""),opportunityId:String(x?.opportunityId||"")||null,sourceSignature:String(x?.sourceSignature||"")||null,mint:String(x?.mint||""),sourceTs:sec(x?.sourceBuyAt)??sec(x?.sourceTimestamp),copySignature:String(x?.followerBuySignature||"")||null});return out;}
function attribute(lot:Lot,cs:Candidate[]){const exact=cs.filter(c=>c.copySignature===lot.signature);if(exact.length===1)return{candidate:exact[0],method:"EXACT_COPY_SIGNATURE",confidence:"HIGH",distanceSec:0};const near=cs.filter(c=>c.mint===lot.mint&&c.sourceTs!=null&&lot.ts>=c.sourceTs-60&&lot.ts-c.sourceTs<=MATCH_WINDOW_SEC).map(c=>({c,d:Math.abs(lot.ts-Number(c.sourceTs))})).sort((a,b)=>a.d-b.d);if(!near.length)return{candidate:null,method:"UNATTRIBUTED",confidence:"NONE",distanceSec:null};const best=near[0]!;const ambiguous=near.length>1&&Math.abs(near[1]!.d-best.d)<30&&near[1]!.c.mirror!==best.c.mirror;if(ambiguous)return{candidate:null,method:"AMBIGUOUS_MINT_TIME",confidence:"LOW",distanceSec:best.d};return{candidate:best.c,method:"UNIQUE_MINT_TIME",confidence:"MEDIUM",distanceSec:best.d};}

export async function buildOdinActualReconciliation(){const generatedAt=new Date().toISOString();const [portfolio,op,truth,follower]=await Promise.all([read(PORTFOLIO_PATH,{events:{}}),read(OPPORTUNITY_PATH,{}),read(TRUTH_PATH,{entries:{}}),read(FOLLOWER_PATH,{entries:{}})]);const lots=buildLots(eventsFromCache(portfolio)),cs=candidates(op,truth,follower);const rows=lots.map(lot=>{const a=attribute(lot,cs),closed=Boolean(lot.resolvedAt)&&lot.soldQty>=lot.qtyInitial*CLOSE_FRACTION,netSol=closed?lot.proceedsSol-lot.costSol:null;return{buySignature:lot.signature,mint:lot.mint,buyAt:new Date(lot.ts*1000).toISOString(),costSol:lot.costSol,soldFraction:lot.qtyInitial>0?Math.min(1,lot.soldQty/lot.qtyInitial):0,proceedsSol:lot.proceedsSol,closed,resolvedAt:lot.resolvedAt,netSol,mirror:a.candidate?.mirror||null,opportunityId:a.candidate?.opportunityId||null,sourceSignature:a.candidate?.sourceSignature||null,attributionMethod:a.method,attributionConfidence:a.confidence,attributionDistanceSec:a.distanceSec};});const closed=rows.filter(r=>r.closed&&typeof r.netSol==="number"),attributed=closed.filter(r=>r.mirror),unattributed=closed.filter(r=>!r.mirror);const byMirror=Object.values(attributed.reduce((acc:any,r:any)=>{const k=r.mirror;const x=acc[k]||{mirror:k,closed:0,wins:0,losses:0,netSol:0};x.closed++;x.netSol+=r.netSol;if(r.netSol>0)x.wins++;else if(r.netSol<0)x.losses++;acc[k]=x;return acc;},{})).sort((a:any,b:any)=>b.netSol-a.netSol);const out={schemaVersion:1,event:"shark_scout_odin_actual_reconciliation_complete",generatedAt,closeFraction:CLOSE_FRACTION,matchWindowSec:MATCH_WINDOW_SEC,summary:{followerLots:rows.length,closedLots:closed.length,openLots:rows.length-closed.length,attributedClosed:attributed.length,unattributedClosed:unattributed.length,attributedNetSol:attributed.reduce((s,r)=>s+Number(r.netSol||0),0),unattributedNetSol:unattributed.reduce((s,r)=>s+Number(r.netSol||0),0),totalClosedNetSol:closed.reduce((s,r)=>s+Number(r.netSol||0),0),governanceSafe:unattributed.length===0},byMirror,rows,notes:["Follower on-chain lots are the authoritative monetary surface.","Exact copy-signature attribution is preferred; mint/time fallback is accepted only when unambiguous.","Unattributed realized lots remain visible and make governanceSafe=false rather than being silently omitted.","This module is observational and does not mutate Odin."]};await atomic(OUT_PATH,out);console.log(JSON.stringify(out));return out;}
if(import.meta.url===`file://${process.argv[1]}`)buildOdinActualReconciliation().catch(e=>{console.error(JSON.stringify({event:"shark_scout_odin_actual_reconciliation_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});