export type FragilityTrip={mint?:string;followerNetSol?:number|null;stress50NetSol?:number|null;buyTimestamp?:string|null;sellTimestamp?:string|null};
const n=(v:any)=>{const x=Number(v);return Number.isFinite(x)?x:null};
const sum=(xs:number[])=>xs.reduce((a,b)=>a+b,0);
const median=(xs:number[])=>{if(!xs.length)return null;const s=[...xs].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
function maxDrawdown(xs:number[]){let eq=0,peak=0,mdd=0;for(const x of xs){eq+=x;peak=Math.max(peak,eq);mdd=Math.max(mdd,peak-eq);}return mdd;}
function rolling(xs:number[],w:number){if(xs.length<w)return null;const avgs:number[]=[];for(let i=0;i<=xs.length-w;i++)avgs.push(sum(xs.slice(i,i+w))/w);return{windows:avgs.length,mean:sum(avgs)/avgs.length,min:Math.min(...avgs),positiveShare:avgs.filter(x=>x>0).length/avgs.length};}
function seedOf(s:string){let h=2166136261>>>0;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h||1;}
function rng(seed:number){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296};}
function bootstrapPositive(xs:number[],seed:string,iters=1000){if(!xs.length)return null;const r=rng(seedOf(seed));let pos=0;for(let k=0;k<iters;k++){let s=0;for(let i=0;i<xs.length;i++)s+=xs[Math.floor(r()*xs.length)]!;if(s/xs.length>0)pos++;}return pos/iters;}
export function tradeLevelFragility(address:string,trips:FragilityTrip[]){const clean=trips.map((t,i)=>({i,mint:String(t?.mint||"UNKNOWN"),net:n(t?.followerNetSol),stress:n(t?.stress50NetSol),ts:Date.parse(String(t?.sellTimestamp||t?.buyTimestamp||""))})).filter(x=>x.net!=null).sort((a,b)=>(Number.isFinite(a.ts)?a.ts:0)-(Number.isFinite(b.ts)?b.ts:0));const xs=clean.map(x=>x.net as number),wins=xs.filter(x=>x>0),losses=xs.filter(x=>x<0),grossWin=sum(wins),grossLoss=Math.abs(sum(losses)),ranked=[...xs].sort((a,b)=>b-a),dropLargest=ranked.slice(1),drop3=ranked.slice(Math.min(3,ranked.length)),drop5pct=ranked.slice(Math.max(1,Math.ceil(ranked.length*.05)));const downside=losses.length?Math.sqrt(losses.reduce((a,b)=>a+b*b,0)/losses.length):0;const token=new Map<string,number>();for(const x of clean)token.set(x.mint,(token.get(x.mint)||0)+(x.net as number));const thirds=[0,1,2].map(i=>{const a=Math.floor(xs.length*i/3),b=i===2?xs.length:Math.floor(xs.length*(i+1)/3),z=xs.slice(a,b);return{trades:z.length,netSol:sum(z),meanSol:z.length?sum(z)/z.length:null};});const stress=clean.map(x=>x.stress).filter((x):x is number=>x!=null);return{trades:xs.length,netSol:sum(xs),medianTradeSol:median(xs),meanTradeSol:xs.length?sum(xs)/xs.length:null,profitFactor:grossLoss>0?grossWin/grossLoss:grossWin>0?999:null,downsideDeviationSol:downside,maxDrawdownSol:maxDrawdown(xs),largestWinnerShare:grossWin>0?(wins.length?Math.max(...wins):0)/grossWin:null,netExLargestWinnerSol:sum(dropLargest),netExTop3Sol:sum(drop3),netExTop5PctSol:sum(drop5pct),rolling10:rolling(xs,10),rolling20:rolling(xs,20),bootstrapProbabilityPositiveExpectancy:bootstrapPositive(xs,address,1000),independentTokens:token.size,profitableTokens:[...token.values()].filter(v=>v>0).length,profitableTokenShare:token.size?[...token.values()].filter(v=>v>0).length/token.size:null,regimeThirds:thirds,positiveRegimeShare:thirds.filter(x=>x.trades&&x.netSol>0).length/thirds.filter(x=>x.trades).length,stress50:{trades:stress.length,netSol:stress.length?sum(stress):null,retention:stress.length&&sum(xs)>0?sum(stress)/sum(xs):null}};}
