import fs from "node:fs";
import path from "node:path";
import { bootstrapProbabilityPositive, metrics, type Layer, type TradeResult } from "./ab_metrics.js";
import { manifestHash, sha256, stableJson } from "./prospective_ab_lab.js";

export type Recommendation="KEEP"|"WATCH"|"DEMOTE"|"PROMOTION-READY"|"INSUFFICIENT DATA";
export type GovernancePolicy={schemaVersion:1;minSamples:number;promotionSamples:number;minBootstrapPositive:number;promotionBootstrapPositive:number;minStress50Sol:number;maxDrawdownSol:number;minProfitFactor:number;degradationWindow:number;degradationTolerance:number;requiredLayer:Layer};
export type WalletDecision={wallet:string;role:string;recommendation:Recommendation;reason:string[];sampleAdequacy:number;confidence:number|null;metrics:ReturnType<typeof metrics>;controlDeltaSol:number|null;degradation:{detected:boolean;recentNetSol:number|null;priorNetSol:number|null;ratio:number|null};policyHash:string;evaluatedAt:string};
type Snapshot={schemaVersion:1;snapshotId:string;at:string;policy:GovernancePolicy;policyHash:string;manifestHash:string;decisions:WalletDecision[];summary:Record<Recommendation,number>;controls:{wallets:string[];n:number;netSol:number;bootstrapPositive:number|null};};
const DEFAULT_POLICY:GovernancePolicy={schemaVersion:1,minSamples:20,promotionSamples:50,minBootstrapPositive:.80,promotionBootstrapPositive:.95,minStress50Sol:0,maxDrawdownSol:1,minProfitFactor:1.15,degradationWindow:15,degradationTolerance:.50,requiredLayer:"ACTUAL_ODIN"};
const iso=()=>new Date().toISOString();
function safeNumber(name:string,fallback:number){const n=Number(process.env[name]);return Number.isFinite(n)?n:fallback;}
function policyFromEnv():GovernancePolicy{return{...DEFAULT_POLICY,minSamples:safeNumber("PACKAGE_D_MIN_SAMPLES",DEFAULT_POLICY.minSamples),promotionSamples:safeNumber("PACKAGE_D_PROMOTION_SAMPLES",DEFAULT_POLICY.promotionSamples),minBootstrapPositive:safeNumber("PACKAGE_D_MIN_BOOTSTRAP_POSITIVE",DEFAULT_POLICY.minBootstrapPositive),promotionBootstrapPositive:safeNumber("PACKAGE_D_PROMOTION_BOOTSTRAP_POSITIVE",DEFAULT_POLICY.promotionBootstrapPositive),minStress50Sol:safeNumber("PACKAGE_D_MIN_STRESS50_SOL",DEFAULT_POLICY.minStress50Sol),maxDrawdownSol:safeNumber("PACKAGE_D_MAX_DRAWDOWN_SOL",DEFAULT_POLICY.maxDrawdownSol),minProfitFactor:safeNumber("PACKAGE_D_MIN_PROFIT_FACTOR",DEFAULT_POLICY.minProfitFactor),degradationWindow:Math.max(5,Math.floor(safeNumber("PACKAGE_D_DEGRADATION_WINDOW",DEFAULT_POLICY.degradationWindow))),degradationTolerance:safeNumber("PACKAGE_D_DEGRADATION_TOLERANCE",DEFAULT_POLICY.degradationTolerance)};}
function readRows(file:string):TradeResult[]{try{return fs.readFileSync(file,"utf8").split("\n").filter(Boolean).map(x=>JSON.parse(x)).filter(x=>x&&typeof x.wallet==="string"&&typeof x.netSol==="number");}catch{return[];}}
function recentDegradation(rows:TradeResult[],window:number,tolerance:number){if(rows.length<window*2)return{detected:false,recentNetSol:null,priorNetSol:null,ratio:null};const ordered=[...rows].sort((a,b)=>String(a.resolvedAt).localeCompare(String(b.resolvedAt))),recent=ordered.slice(-window),prior=ordered.slice(-window*2,-window),rn=recent.reduce((s,x)=>s+x.netSol,0),pn=prior.reduce((s,x)=>s+x.netSol,0),ratio=pn>0?rn/pn:null;return{detected:pn>0&&rn<pn*tolerance,recentNetSol:rn,priorNetSol:pn,ratio};}
export class PackageDGovernance{
 private readonly root:string;private readonly resultsPath:string;private readonly snapshotsPath:string;private readonly policy:GovernancePolicy;private readonly policyHash:string;
 constructor(root:string,private readonly manifest:string,private readonly live:Set<string>,private readonly research:Set<string>,private readonly controls:Set<string>){this.root=root;this.resultsPath=path.join(root,"experiment-results.jsonl");this.snapshotsPath=path.join(root,"governance-snapshots.jsonl");this.policy=policyFromEnv();this.policyHash=manifestHash(this.policy);}
 evaluate():Omit<Snapshot,"snapshotId">{const all=readRows(this.resultsPath),layer=this.policy.requiredLayer,eligible=all.filter(x=>x.layer===layer),controlRows=eligible.filter(x=>this.controls.has(x.wallet)),controlMetrics=metrics(controlRows),controlConfidence=bootstrapProbabilityPositive(controlRows),wallets=new Set([...this.live,...this.research]);const decisions:WalletDecision[]=[];
  for(const wallet of wallets){const rows=eligible.filter(x=>x.wallet===wallet),m=metrics(rows),confidence=bootstrapProbabilityPositive(rows),adequacy=Math.min(1,rows.length/this.policy.promotionSamples),degradation=recentDegradation(rows,this.policy.degradationWindow,this.policy.degradationTolerance),reasons:string[]=[];let recommendation:Recommendation="WATCH";const controlDelta=controlRows.length?m.netSol-(controlMetrics.netSol/Math.max(1,this.controls.size)):null;
   if(rows.length<this.policy.minSamples){recommendation="INSUFFICIENT DATA";reasons.push(`sample ${rows.length}/${this.policy.minSamples}`);}else{const pf=m.profitFactor??0,basePass=(confidence??0)>=this.policy.minBootstrapPositive&&m.stress50>=this.policy.minStress50Sol&&m.maxDrawdown<=this.policy.maxDrawdownSol&&pf>=this.policy.minProfitFactor;
    if(degradation.detected){recommendation=this.live.has(wallet)?"WATCH":"DEMOTE";reasons.push("recent performance degraded versus prior window");}
    else if(!basePass){recommendation=this.live.has(wallet)?"WATCH":"DEMOTE";if((confidence??0)<this.policy.minBootstrapPositive)reasons.push("confidence below threshold");if(m.stress50<this.policy.minStress50Sol)reasons.push("stress50 below threshold");if(m.maxDrawdown>this.policy.maxDrawdownSol)reasons.push("drawdown above threshold");if(pf<this.policy.minProfitFactor)reasons.push("profit factor below threshold");}
    else if(!this.live.has(wallet)&&rows.length>=this.policy.promotionSamples&&(confidence??0)>=this.policy.promotionBootstrapPositive&&(controlDelta===null||controlDelta>0)){recommendation="PROMOTION-READY";reasons.push("prospective thresholds passed");if(controlDelta!==null)reasons.push("outperformed near-miss controls");}
    else{recommendation="KEEP";reasons.push("prospective thresholds passed");}}
   decisions.push({wallet,role:this.live.has(wallet)?"LIVE_SOURCE":"RESEARCH",recommendation,reason:reasons,sampleAdequacy:adequacy,confidence,metrics:m,controlDeltaSol:controlDelta,degradation,policyHash:this.policyHash,evaluatedAt:iso()});}
  const summary:Record<Recommendation,number>={"KEEP":0,"WATCH":0,"DEMOTE":0,"PROMOTION-READY":0,"INSUFFICIENT DATA":0};for(const d of decisions)summary[d.recommendation]++;
  return{schemaVersion:1,at:iso(),policy:this.policy,policyHash:this.policyHash,manifestHash:this.manifest,decisions:decisions.sort((a,b)=>a.wallet.localeCompare(b.wallet)),summary,controls:{wallets:[...this.controls].sort(),n:controlRows.length,netSol:controlMetrics.netSol,bootstrapPositive:controlConfidence}};}
 snapshot():Snapshot{const e=this.evaluate(),snapshot:Snapshot={...e,snapshotId:sha256(stableJson({at:e.at,policyHash:e.policyHash,manifestHash:e.manifestHash,decisions:e.decisions}))};fs.mkdirSync(this.root,{recursive:true});fs.appendFileSync(this.snapshotsPath,JSON.stringify(snapshot)+"\n");return snapshot;}
 status(){const e=this.evaluate();return{...e,guardrails:{advisoryOnly:true,odinMutation:false,capitalMutation:false,mirrorMutation:false},snapshotsPath:this.snapshotsPath};}
}
