import { promises as fs } from "node:fs";
import path from "node:path";

const OUT_PATH=process.env.SCOUT_PRODUCTION_TRUTH_PATH||"/data/production-truth-health.json";
const HISTORY_PATH=process.env.SCOUT_PRODUCTION_TRUTH_HISTORY_PATH||"/data/production-truth-health.jsonl";
const PIPELINE_PATH=process.env.SCOUT_PIPELINE_TRUTH_PATH||"/data/pipeline-truth.json";
const REPLAY_PATH=process.env.SCOUT_REPLAY_SHADOW_PATH||"/data/replay-shadow.json";
const REPLAY_FALLBACK_PATH="./data/replay-shadow.json";
const CANONICAL_TELEMETRY_PATH=process.env.SCOUT_CANONICAL_RESCUE_TELEMETRY_PATH||"/data/canonical-replay/rescue-telemetry.json";
const AB_STATUS_URL=process.env.SHARK_AB_STATUS_URL||"https://shark-scout-alchemy-ab-production.up.railway.app/prospective/status";
const REQUEST_TIMEOUT_MS=Math.max(2000,Math.min(15000,Number(process.env.SHARK_AB_STATUS_TIMEOUT_MS||8000)));

type AnyObj=Record<string,any>;
type ChannelState="HEALTHY"|"HEALTHY_IDLE"|"DEGRADED"|"STALE"|"UNAVAILABLE"|"NO_ACTIVITY"|"UNKNOWN";
function now(){return new Date().toISOString();}
function ageMs(v:any){const t=Date.parse(String(v||""));return Number.isFinite(t)?Math.max(0,Date.now()-t):null;}
function ts(v:any){const t=Date.parse(String(v||""));return Number.isFinite(t)?t:0;}
function count(v:any){const n=Number(v||0);return Number.isFinite(n)?n:0;}
function delta(current:any,prior:any){if(prior==null)return null;return Math.max(0,count(current)-count(prior));}
async function readJson(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomic(file:string,data:any){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(data,null,2));await fs.rename(tmp,file);}
async function fetchStatus(){const c=new AbortController(),timer=setTimeout(()=>c.abort(),REQUEST_TIMEOUT_MS);try{const r=await fetch(AB_STATUS_URL,{signal:c.signal,headers:{accept:"application/json"}});const text=await r.text();if(!r.ok)throw new Error(`HTTP_${r.status}:${text.slice(0,160)}`);return JSON.parse(text);}finally{clearTimeout(timer);}}
async function freshestReplay(){const candidates=await Promise.all([readJson(REPLAY_PATH,null),REPLAY_FALLBACK_PATH===REPLAY_PATH?Promise.resolve(null):readJson(REPLAY_FALLBACK_PATH,null)]);return candidates.filter(Boolean).sort((a,b)=>ts(b?.finishedAt)-ts(a?.finishedAt))[0]||null;}
function canonicalSummary(replay:any,pipeline:any){const c=replay?.canonicalRescue||{},rows=Array.isArray(replay?.rows)?replay.rows:[],ambiguity:Record<string,number>={};let budgetExhausted=0;for(const row of rows){for(const [k,v] of Object.entries(row?.diagnostics?.ambiguousReasons||{}))ambiguity[k]=(ambiguity[k]||0)+Number(v||0);budgetExhausted+=Number(row?.canonicalRescue?.reasonCodes?.RESCUE_BUDGET_EXHAUSTED||0);}const finishedAt=replay?.finishedAt||null,replayTs=ts(finishedAt),runStartedTs=ts(pipeline?.startedAt),freshForRun=Boolean(replay?.event)&&replayTs>0&&(runStartedTs>0?replayTs>=runStartedTs:Date.now()-replayTs<30*60_000);return{available:freshForRun,reason:freshForRun?null:replay?.event?"STALE_REPLAY_FOR_CURRENT_RUN":"CANONICAL_RESCUE_TELEMETRY_UNAVAILABLE",finishedAt,ageMs:ageMs(finishedAt),walletsExamined:Number(replay?.walletsExamined||0),canonicalPersisted:Number(replay?.canonicalPersisted||0),attempted:Number(c?.attempted||0),cacheHits:Number(c?.cacheHits||0),resolved:Number(c?.resolved||0),failed:Number(c?.failed||0),remainingBudget:Number(c?.remainingBudget||0),cacheHitRate:c?.cacheHitRate??null,effectiveResolutionRate:c?.effectiveResolutionRate??null,rpcCallsPerResolved:c?.rpcCallsPerResolved??null,providers:c?.providers||{},unresolvedReasons:c?.unresolvedReasons||{},ambiguityReasons:ambiguity,budgetExhaustedTransactions:budgetExhausted,sourcePath:replay===null?null:(REPLAY_PATH),telemetryFile:CANONICAL_TELEMETRY_PATH};}
function channelHealth(status:any,priorChannels:any){const s=status?.state||{},runtime=status?.runtime||{},rel=status?.reliability||{},manifest=status?.manifest||{},expected=1+(Array.isArray(manifest?.live)?manifest.live.length:0)+(Array.isArray(manifest?.research)?manifest.research.length:0)+(Array.isArray(manifest?.controls)?manifest.controls.length:0),subs=Number(runtime?.wssSubscriptions||0),verified=Number(s?.verified||0),received=Number(s?.received||0),rejected=Number(s?.rejectedSignature||0),malformed=Number(s?.malformed||0),reconcileErrors=Number(s?.reconcileErrors||0),wssErrors=Number(s?.wssErrors||0),lastVerifiedAgeMs=ageMs(s?.lastVerifiedAt),lastReconcileAgeMs=ageMs(rel?.lastReconcileAt),integrityErrors=Number(rel?.integrityErrors||0),manifestDrift=Boolean(rel?.manifestDrift),reliabilityState=String(rel?.severity||rel?.status||"").toUpperCase();
 const rejectedDelta=delta(rejected,priorChannels?.rejectedSignature),malformedDelta=delta(malformed,priorChannels?.malformed),reconcileErrorsDelta=delta(reconcileErrors,priorChannels?.reconcileErrors),wssErrorsDelta=delta(wssErrors,priorChannels?.wssErrors),receivedDelta=delta(received,priorChannels?.received),verifiedDelta=delta(verified,priorChannels?.verified),rpcDelta=delta(s?.rpcReconciled,priorChannels?.rpcReconciled),wssSeenDelta=delta(s?.wssSeen,priorChannels?.wssSeen);
 const webhookCurrentError=(rejectedDelta??0)>0||(malformedDelta??0)>0;
 const rpcCurrentError=(reconcileErrorsDelta??0)>0;
 const wssCurrentError=(wssErrorsDelta??0)>0;
 const reliabilityDegraded=reliabilityState.includes("ERROR")||reliabilityState.includes("DEGRADED")||reliabilityState.includes("CRITICAL");
 const webhook:ChannelState=status?.prospectiveEligibility!=="VERIFIED_ONLY"?"DEGRADED":webhookCurrentError?"DEGRADED":verified>0?(lastVerifiedAgeMs!=null&&lastVerifiedAgeMs>6*60*60_000?"HEALTHY_IDLE":"HEALTHY"):(received>0?"HEALTHY_IDLE":"NO_ACTIVITY");
 const rpc:ChannelState=!runtime?.rpc?"UNAVAILABLE":lastReconcileAgeMs==null?"UNKNOWN":lastReconcileAgeMs>5*60_000?"STALE":rpcCurrentError?"DEGRADED":"HEALTHY";
 const wss:ChannelState=!runtime?.wss?"UNAVAILABLE":subs!==expected?"DEGRADED":wssCurrentError?"DEGRADED":Number(s?.wssSeen||0)>0?"HEALTHY":"HEALTHY_IDLE";
 const persistence:ChannelState=integrityErrors>0||manifestDrift||reliabilityDegraded?"DEGRADED":"HEALTHY";
 const states=[webhook,rpc,wss,persistence],overall:ChannelState=states.includes("UNAVAILABLE")||states.includes("STALE")?"DEGRADED":states.includes("DEGRADED")?"DEGRADED":"HEALTHY";
 return{overall,webhook,rpc,wss,persistence,expectedTrackedWallets:expected,wssSubscriptions:subs,received,verified,rejectedSignature:rejected,malformed,envelopes:Number(s?.envelopes||0),rpcReconciled:Number(s?.rpcReconciled||0),wssSeen:Number(s?.wssSeen||0),reconcileErrors,wssErrors,lastReceivedAt:s?.lastReceivedAt||null,lastVerifiedAt:s?.lastVerifiedAt||null,lastVerifiedAgeMs,lastReconcileAt:rel?.lastReconcileAt||null,lastReconcileAgeMs,recoveredSourceEvents:Number(s?.recoveredSourceEvents||0),manifestHash:manifest?.hash||null,integrityErrors,manifestDrift,prospectiveEligibility:status?.prospectiveEligibility||null,reliabilityState:reliabilityState||null,window:{baselineAvailable:Boolean(priorChannels),receivedDelta,verifiedDelta,rejectedSignatureDelta:rejectedDelta,malformedDelta,rpcReconciledDelta:rpcDelta,reconcileErrorsDelta,wssSeenDelta,wssErrorsDelta},semantics:{lifetimeCounters:"Preserved for audit only; historical errors do not permanently degrade current health.",windowCounters:"Current health is degraded only by new errors since the prior production-truth snapshot, stale channels, manifest/integrity failure, or current Package C degradation."}};}

async function main(){const startedAt=now(),[priorHealth,pipeline,replay]=await Promise.all([readJson(OUT_PATH,null),readJson(PIPELINE_PATH,null),freshestReplay()]);let ab:any=null,abError:string|null=null;try{ab=await fetchStatus();}catch(e){abError=e instanceof Error?e.message:String(e);}const channels=ab?channelHealth(ab,priorHealth?.ab?.channels):{overall:"UNAVAILABLE" as ChannelState,webhook:"UNAVAILABLE" as ChannelState,rpc:"UNAVAILABLE" as ChannelState,wss:"UNAVAILABLE" as ChannelState,persistence:"UNKNOWN" as ChannelState};const pipelineSummary={available:Boolean(pipeline),status:pipeline?.status||"UNKNOWN",startedAt:pipeline?.startedAt||null,finishedAt:pipeline?.finishedAt||null,ageMs:ageMs(pipeline?.finishedAt),failedCount:Number(pipeline?.failedCount||0),skippedBudgetCount:Number(pipeline?.skippedBudgetCount||0),skippedProviderCount:Number(pipeline?.skippedProviderCount||0)};const canonical=canonicalSummary(replay,pipeline);if(canonical.available)await atomic(CANONICAL_TELEMETRY_PATH,{schemaVersion:1,event:"shark_scout_canonical_rescue_telemetry",persistedAt:now(),runStartedAt:pipeline?.startedAt||null,...canonical});const findings:string[]=[];if(channels.overall!=="HEALTHY")findings.push(`AB_CHANNELS_${channels.overall}`);if(pipelineSummary.available&&!['RUNNING','COMPLETE'].includes(pipelineSummary.status))findings.push(`PIPELINE_${pipelineSummary.status}`);if(!canonical.available)findings.push(canonical.reason||"CANONICAL_RESCUE_TELEMETRY_UNAVAILABLE");if(canonical.budgetExhaustedTransactions>0||canonical.remainingBudget===0&&canonical.attempted>0)findings.push("CANONICAL_RESCUE_BUDGET_EXHAUSTED");if(canonical.effectiveResolutionRate!=null&&Number(canonical.effectiveResolutionRate)>0)findings.push("CANONICAL_RESCUE_PRODUCTIVE");const out={schemaVersion:2,event:"shark_scout_production_truth_health",startedAt,finishedAt:now(),serviceAlive:Boolean(ab?.ok),systemHealthy:Boolean(ab?.ok)&&channels.overall==="HEALTHY"&&canonical.available,ab:{reachable:Boolean(ab),error:abError,version:ab?.version||null,channels,metrics:ab?.metrics||null,reliability:ab?.reliability||null},pipeline:pipelineSummary,canonical,findings,semantics:{serviceAlive:"HTTP/service process reachable only; not proof that data channels, evidence freshness, canonical telemetry, or hourly pipeline are healthy",systemHealthy:"A/B current-window channels are non-degraded and current-run canonical telemetry is available; hourly completion remains independently persisted in pipeline-truth.json",noActivity:"No webhook/WSS event is not treated as failure when subscriptions, persistence, and reconciliation are healthy",historicalErrors:"Lifetime counters remain visible for audit but do not poison current health after the condition has cleared"}};await atomic(OUT_PATH,out);await fs.appendFile(HISTORY_PATH,JSON.stringify(out)+"\n");console.log(JSON.stringify(out));}
main().catch(e=>{console.error(JSON.stringify({event:"shark_scout_production_truth_health_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});