import { promises as fs } from "node:fs";
import path from "node:path";

const OUT_PATH=process.env.SCOUT_PRODUCTION_TRUTH_PATH||"/data/production-truth-health.json";
const HISTORY_PATH=process.env.SCOUT_PRODUCTION_TRUTH_HISTORY_PATH||"/data/production-truth-health.jsonl";
const PIPELINE_PATH=process.env.SCOUT_PIPELINE_TRUTH_PATH||"/data/pipeline-truth.json";
const REPLAY_PATH=process.env.SCOUT_REPLAY_SHADOW_PATH||"/data/replay-shadow.json";
const AB_STATUS_URL=process.env.SHARK_AB_STATUS_URL||"https://shark-scout-alchemy-ab-production.up.railway.app/prospective/status";
const REQUEST_TIMEOUT_MS=Math.max(2000,Math.min(15000,Number(process.env.SHARK_AB_STATUS_TIMEOUT_MS||8000)));

type AnyObj=Record<string,any>;
type ChannelState="HEALTHY"|"HEALTHY_IDLE"|"DEGRADED"|"STALE"|"UNAVAILABLE"|"NO_ACTIVITY"|"UNKNOWN";
function now(){return new Date().toISOString();}
function ageMs(v:any){const t=Date.parse(String(v||""));return Number.isFinite(t)?Math.max(0,Date.now()-t):null;}
async function readJson(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomic(file:string,data:any){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(data,null,2));await fs.rename(tmp,file);}
async function fetchStatus(){const c=new AbortController(),timer=setTimeout(()=>c.abort(),REQUEST_TIMEOUT_MS);try{const r=await fetch(AB_STATUS_URL,{signal:c.signal,headers:{accept:"application/json"}});const text=await r.text();if(!r.ok)throw new Error(`HTTP_${r.status}:${text.slice(0,160)}`);return JSON.parse(text);}finally{clearTimeout(timer);}}
function canonicalSummary(replay:any){const c=replay?.canonicalRescue||{},rows=Array.isArray(replay?.rows)?replay.rows:[],ambiguity:Record<string,number>={};let budgetExhausted=0;for(const row of rows){for(const [k,v] of Object.entries(row?.diagnostics?.ambiguousReasons||{}))ambiguity[k]=(ambiguity[k]||0)+Number(v||0);budgetExhausted+=Number(row?.canonicalRescue?.reasonCodes?.RESCUE_BUDGET_EXHAUSTED||0);}return{available:Boolean(replay?.event),finishedAt:replay?.finishedAt||null,ageMs:ageMs(replay?.finishedAt),walletsExamined:Number(replay?.walletsExamined||0),canonicalPersisted:Number(replay?.canonicalPersisted||0),attempted:Number(c?.attempted||0),cacheHits:Number(c?.cacheHits||0),resolved:Number(c?.resolved||0),failed:Number(c?.failed||0),remainingBudget:Number(c?.remainingBudget||0),cacheHitRate:c?.cacheHitRate??null,effectiveResolutionRate:c?.effectiveResolutionRate??null,rpcCallsPerResolved:c?.rpcCallsPerResolved??null,providers:c?.providers||{},unresolvedReasons:c?.unresolvedReasons||{},ambiguityReasons:ambiguity,budgetExhaustedTransactions:budgetExhausted};}
function channelHealth(status:any){const s=status?.state||{},runtime=status?.runtime||{},rel=status?.reliability||{},manifest=status?.manifest||{},expected=1+(Array.isArray(manifest?.live)?manifest.live.length:0)+(Array.isArray(manifest?.research)?manifest.research.length:0)+(Array.isArray(manifest?.controls)?manifest.controls.length:0),subs=Number(runtime?.wssSubscriptions||0),verified=Number(s?.verified||0),received=Number(s?.received||0),rejected=Number(s?.rejectedSignature||0),malformed=Number(s?.malformed||0),reconcileErrors=Number(s?.reconcileErrors||0),wssErrors=Number(s?.wssErrors||0),lastVerifiedAgeMs=ageMs(s?.lastVerifiedAt),lastReconcileAgeMs=ageMs(rel?.lastReconcileAt),integrityErrors=Number(rel?.integrityErrors||0),manifestDrift=Boolean(rel?.manifestDrift);
 const webhook:ChannelState=status?.prospectiveEligibility!=="VERIFIED_ONLY"?"DEGRADED":rejected>0||malformed>0?"DEGRADED":verified>0?(lastVerifiedAgeMs!=null&&lastVerifiedAgeMs>6*60*60_000?"HEALTHY_IDLE":"HEALTHY"):(received>0?"DEGRADED":"NO_ACTIVITY");
 const rpc:ChannelState=!runtime?.rpc?"UNAVAILABLE":lastReconcileAgeMs==null?"UNKNOWN":lastReconcileAgeMs>5*60_000?"STALE":reconcileErrors>0?"DEGRADED":"HEALTHY";
 const wss:ChannelState=!runtime?.wss?"UNAVAILABLE":subs!==expected?"DEGRADED":wssErrors>0?"DEGRADED":Number(s?.wssSeen||0)>0?"HEALTHY":"HEALTHY_IDLE";
 const persistence:ChannelState=integrityErrors>0||manifestDrift?"DEGRADED":"HEALTHY";
 const states=[webhook,rpc,wss,persistence],overall:ChannelState=states.includes("UNAVAILABLE")||states.includes("STALE")?"DEGRADED":states.includes("DEGRADED")?"DEGRADED":"HEALTHY";
 return{overall,webhook,rpc,wss,persistence,expectedTrackedWallets:expected,wssSubscriptions:subs,received,verified,rejectedSignature:rejected,malformed,envelopes:Number(s?.envelopes||0),rpcReconciled:Number(s?.rpcReconciled||0),wssSeen:Number(s?.wssSeen||0),reconcileErrors,wssErrors,lastReceivedAt:s?.lastReceivedAt||null,lastVerifiedAt:s?.lastVerifiedAt||null,lastVerifiedAgeMs,lastReconcileAt:rel?.lastReconcileAt||null,lastReconcileAgeMs,recoveredSourceEvents:Number(s?.recoveredSourceEvents||0),manifestHash:manifest?.hash||null,integrityErrors,manifestDrift,prospectiveEligibility:status?.prospectiveEligibility||null};}

async function main(){const startedAt=now(),[priorPipeline,replay]=await Promise.all([readJson(PIPELINE_PATH,null),readJson(REPLAY_PATH,null)]);let ab:any=null,abError:string|null=null;try{ab=await fetchStatus();}catch(e){abError=e instanceof Error?e.message:String(e);}const channels=ab?channelHealth(ab):{overall:"UNAVAILABLE" as ChannelState,webhook:"UNAVAILABLE" as ChannelState,rpc:"UNAVAILABLE" as ChannelState,wss:"UNAVAILABLE" as ChannelState,persistence:"UNKNOWN" as ChannelState};const pipeline={available:Boolean(priorPipeline),status:priorPipeline?.status||"UNKNOWN",finishedAt:priorPipeline?.finishedAt||null,ageMs:ageMs(priorPipeline?.finishedAt),failedCount:Number(priorPipeline?.failedCount||0),skippedBudgetCount:Number(priorPipeline?.skippedBudgetCount||0),skippedProviderCount:Number(priorPipeline?.skippedProviderCount||0)};const canonical=canonicalSummary(replay);const findings:string[]=[];if(channels.overall!=="HEALTHY")findings.push(`AB_CHANNELS_${channels.overall}`);if(pipeline.available&&pipeline.status!=="COMPLETE")findings.push(`PRIOR_PIPELINE_${pipeline.status}`);if(canonical.budgetExhaustedTransactions>0)findings.push("CANONICAL_RESCUE_BUDGET_EXHAUSTED");if(canonical.effectiveResolutionRate!=null&&Number(canonical.effectiveResolutionRate)>0)findings.push("CANONICAL_RESCUE_PRODUCTIVE");const out={schemaVersion:1,event:"shark_scout_production_truth_health",startedAt,finishedAt:now(),serviceAlive:Boolean(ab?.ok),systemHealthy:Boolean(ab?.ok)&&channels.overall==="HEALTHY",ab:{reachable:Boolean(ab),error:abError,version:ab?.version||null,channels,metrics:ab?.metrics||null,reliability:ab?.reliability||null},priorPipeline:pipeline,canonical,findings,semantics:{serviceAlive:"HTTP/service process reachable only; not proof that data channels or hourly pipeline are healthy",systemHealthy:"A/B channels are non-degraded; hourly completion remains independently persisted in pipeline-truth.json",noActivity:"No webhook/WSS event is not treated as failure when subscriptions and reconciliation are healthy"}};await atomic(OUT_PATH,out);await fs.appendFile(HISTORY_PATH,JSON.stringify(out)+"\n");console.log(JSON.stringify(out));}
main().catch(e=>{console.error(JSON.stringify({event:"shark_scout_production_truth_health_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});