export type PromotionStatus="UNKNOWN"|"REJECT"|"SIGNAL_ONLY"|"DEEP_DIVE"|"ODIN_PROSPECT";
export type SampleQuality={risk:"HIGH"|"MEDIUM"|"LOW";reasons:string[];closed:number;buys:number;coverage:number|null;discoveryContexts:number};
export type CappedReplay={dailyCap:number;selected:number;netSol:number;stress50NetSol:number;stress75NetSol:number;winRate:number|null};
export type PromotionVerdict={status:PromotionStatus;stage:string;reasons:string[];rp:CappedReplay;q:SampleQuality};
export const PROMOTION_CONTRACT_VERSION="odin_promotion_v4_canonical_behavior";
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:null;}
function sum(xs:number[]){return xs.reduce((a,b)=>a+b,0);}
function tripTs(v:any){const x=n(v);return x==null?null:(x>1e12?x/1000:x);}
function median(xs:number[]){if(!xs.length)return null;const s=[...xs].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2;}
export function isPromotionStatus(v:any):v is "DEEP_DIVE"|"ODIN_PROSPECT"{return v==="DEEP_DIVE"||v==="ODIN_PROSPECT";}
export function canonicalMedianHoldSeconds(r:any){const tr=Array.isArray(r?.canonicalReplay?.roundTrips)?r.canonicalReplay.roundTrips:[];const holds=tr.map((x:any)=>{const b=tripTs(x?.buyTimestamp),s=tripTs(x?.sellTimestamp);return b!=null&&s!=null&&s>b?s-b:null;}).filter((x:any):x is number=>x!=null&&x>0);return holds.length>=3?median(holds):null;}
export function cappedReplay(trips:any[],dailyCap=2):CappedReplay{const groups=new Map<string,any[]>();for(const r of trips){const k=`${r.mint}|${r.buyTimestamp}`,a=groups.get(k)||[];a.push(r);groups.set(k,a);}const entries=[...groups.values()].sort((a,b)=>Number(a[0]?.buyTimestamp)-Number(b[0]?.buyTimestamp)),daily=new Map<string,number>();let selected=0,netSol=0,stress50NetSol=0,stress75NetSol=0,wins=0;for(const g of entries){const f=g[0],ts=Number(f?.buyTimestamp||0);if(!Number.isFinite(ts)||ts<=0)continue;const day=new Date(ts*1000).toISOString().slice(0,10);if((daily.get(day)||0)>=dailyCap)continue;const ns=g.map(x=>n(x?.followerNetSol)).filter((x):x is number=>x!=null);if(!ns.length)continue;const x=sum(ns);netSol+=x;stress50NetSol+=sum(g.map(x=>n(x?.stress50NetSol)).filter((x):x is number=>x!=null));stress75NetSol+=sum(g.map(x=>n(x?.stress75NetSol)).filter((x):x is number=>x!=null));if(x>0)wins++;selected++;daily.set(day,(daily.get(day)||0)+1);}return{dailyCap,selected,netSol,stress50NetSol,stress75NetSol,winRate:selected?wins/selected:null};}
export function sampleQuality(r:any,w:any):SampleQuality{const cr=r?.canonicalReplay||{},trusted=Math.max(0,Number(cr?.trusted?.trades||0)),closed=Math.max(Number(r?.hold?.closedHolds||0),trusted),buys=Number(r?.hold?.buyEvents||0),canonicalComplete=cr?.historyComplete===true,partial=canonicalComplete?false:Boolean(r?.heliusCoveragePartial||cr?.historyComplete===false),disc=Number(r?.discoveryTokens||w?.tokens?.length||0),coverage=buys>0?Math.min(1,closed/buys):null;let risk=0;const reasons:string[]=[];if(partial){risk=2;reasons.push("canonical_history_partial");}if(closed<10){risk=2;reasons.push("closed_sample_lt_10");}else if(closed<20){risk=Math.max(risk,1);reasons.push("closed_sample_lt_20");}if(disc<2){risk=Math.max(risk,1);reasons.push("single_discovery_context");}if(coverage!=null&&coverage<.35){risk=2;reasons.push("low_close_to_buy_coverage");}return{risk:risk>=2?"HIGH":risk===1?"MEDIUM":"LOW",reasons,closed,buys,coverage,discoveryContexts:disc};}
export function evaluatePromotion(r:any,w:any):PromotionVerdict{const canonicalMed=canonicalMedianHoldSeconds(r),med=canonicalMed??n(r?.hold?.medianHoldSeconds),cr=r?.canonicalReplay,tr=Array.isArray(cr?.roundTrips)?cr.roundTrips:[],t=cr?.trusted||{},q=sampleQuality(r,w),rp=cappedReplay(tr,2),largest=n(t?.largestWinnerShare),reasons:string[]=[];if(med==null)return{status:"UNKNOWN",stage:"hold_unknown",reasons:["median_hold_unknown"],rp,q};if(med<600)return{status:"REJECT",stage:"hold_time",reasons:["median_hold_under_10m"],rp,q};if(med<3600)return{status:"SIGNAL_ONLY",stage:"hold_time",reasons:["median_hold_10m_to_1h"],rp,q};const trades=Number(t?.trades||0),net=n(t?.netSol),s50=n(t?.stress50NetSol);if(trades>=10&&net!=null&&net<=0)return{status:"REJECT",stage:"canonical_economics",reasons:["canonical_net_nonpositive"],rp,q};if(largest!=null&&largest>.60&&trades>=10)return{status:"REJECT",stage:"canonical_robustness",reasons:["largest_winner_over_60pct"],rp,q};const independent=q.discoveryContexts>=2,common=trades>=10&&net!=null&&net>0&&s50!=null&&s50>0&&rp.selected>=5&&rp.netSol>0&&rp.stress50NetSol>0&&largest!=null&&largest<=.60&&q.risk!=="HIGH"&&independent;if(med>=21600&&common&&q.closed>=10)return{status:"DEEP_DIVE",stage:"canonical_odin_replay",reasons:[canonicalMed!=null?"canonical_median_hold_6h_plus":"median_hold_6h_plus","canonical_trades_10_plus","two_per_day_positive","stress50_positive","anti_jackpot","multi_context"],rp,q};const prospect=trades>=15&&net!=null&&net>0&&s50!=null&&s50>0&&rp.selected>=5&&rp.netSol>0&&rp.stress50NetSol>0&&rp.stress75NetSol>0&&largest!=null&&largest<=.45&&q.risk!=="HIGH"&&q.closed>=10&&independent;if(med>=3600&&med<21600&&prospect)return{status:"ODIN_PROSPECT",stage:"canonical_odin_replay",reasons:[canonicalMed!=null?"canonical_median_hold_1h_to_6h":"median_hold_1h_to_6h","canonical_trades_15_plus","two_per_day_positive","stress75_positive","largest_winner_share_lte_45pct","multi_context"],rp,q};reasons.push(trades<10?"canonical_trades_lt_10":"canonical_sample_present");if(net==null)reasons.push("canonical_net_unknown");else if(net>0)reasons.push("canonical_net_positive");if(s50==null)reasons.push("stress50_unknown");else if(s50>0)reasons.push("stress50_positive");if(!independent)reasons.push("single_discovery_context");if(q.risk==="HIGH")reasons.push(...q.reasons.map(x=>`sample:${x}`));return{status:"SIGNAL_ONLY",stage:"needs_more_canonical_evidence",reasons,rp,q};}
