import { promises as fs } from "node:fs";
import path from "node:path";

const FUNNEL_PATH=process.env.SCOUT_EVIDENCE_FUNNEL_PATH||"/data/evidence-funnel.json";
const CANDIDATE_PATH=process.env.SCOUT_CANDIDATE_ENGINE_REPORT_PATH||"/data/candidate-engine-report.json";
const ACTUAL_PATH=process.env.SCOUT_ODIN_ACTUAL_RECONCILIATION_PATH||"/data/odin-actual-reconciliation.json";
const ODIN_PATH=process.env.SCOUT_ODIN_SNAPSHOT_PATH||"/data/odin-config.json";
const OUT_PATH=process.env.SCOUT_REPLACEMENT_LADDER_PATH||"/data/replacement-ladder.json";
const STATE_PATH=process.env.SCOUT_REPLACEMENT_LADDER_STATE_PATH||"/data/replacement-ladder-state.json";
const TOP=Math.max(5,Math.min(30,Number(process.env.REPLACEMENT_LADDER_TOP||15)));

type AnyObj=Record<string,any>;
async function read(file:string,fallback:any){try{return JSON.parse(await fs.readFile(file,"utf8"));}catch{return fallback;}}
async function atomic(file:string,data:any){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(data,null,2));await fs.rename(tmp,file);}
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:null;}
function baseTier(x:any){const trades=n(x?.replay?.trades)||0,net=n(x?.replay?.net),stress=n(x?.replay?.stress50),hold=n(x?.medianHoldHours)||0,risk=String(x?.sampleQuality?.risk||"HIGH"),actionable=Boolean(x?.actionable),blockers=Array.isArray(x?.blockers)?x.blockers:[];if(actionable&&trades>=25&&(net??0)>0&&(stress??0)>0&&hold>=1&&risk==="LOW")return"GOD";if(actionable&&trades>=10&&(net??0)>0&&(stress??0)>0&&hold>=1)return"HISTORICAL_READY";if((net??-1)>0&&(stress??-1)>0&&trades>=10&&hold>=1&&blockers.length<=2)return"SHADOW";if((net??-1)>0&&(stress??-1)>0&&trades>=5)return"NEAR_PASS";return"REJECT";}
function score(x:any){const trades=n(x?.replay?.trades)||0,net=n(x?.replay?.net)||0,stress=n(x?.replay?.stress50)||0,hold=n(x?.medianHoldHours)||0,risk=String(x?.sampleQuality?.risk||"HIGH");let s=Number(x?.nearPassScore||0);s+=Math.min(30,trades/2);s+=net>0?Math.min(30,Math.log10(1+net)*20):Math.max(-30,net*10);s+=stress>0?20:-20;s+=hold>=1?10:0;s+=risk==="LOW"?15:risk==="MEDIUM"?5:-10;return Math.round(s*10)/10;}
export async function buildReplacementLadder(){
  const generatedAt=new Date().toISOString();
  const [funnel,candidate,actual,odin,prior]=await Promise.all([read(FUNNEL_PATH,{}),read(CANDIDATE_PATH,{}),read(ACTUAL_PATH,{}),read(ODIN_PATH,{}),read(STATE_PATH,{tiers:{}})]);
  const candidateMap=new Map((Array.isArray(candidate?.candidates)?candidate.candidates:[]).map((x:any)=>[String(x?.address||""),x]));
  const pool=[...(Array.isArray(funnel?.topActionable)?funnel.topActionable:[]),...(Array.isArray(funnel?.topNearPasses)?funnel.topNearPasses:[]),...(Array.isArray(funnel?.topSampleQualityBlocks)?funnel.topSampleQualityBlocks:[]),...(Array.isArray(funnel?.topReplayBlocks)?funnel.topReplayBlocks:[])];
  const seen=new Set<string>(),rows:any[]=[];
  for(const x of pool){const address=String(x?.address||"");if(!address||seen.has(address))continue;seen.add(address);const ce=candidateMap.get(address) as AnyObj|undefined;const candidateStage=String(ce?.stage||"");const historicalTier=baseTier(x);let t=historicalTier;if(candidateStage==="ODIN_TRIAL_READY")t="TRIAL_READY";else if(candidateStage==="SHADOW_TRIAL"||candidateStage==="SHADOW_EXTEND")t="SHADOW_TRIAL";else if(candidateStage==="SHADOW_FAIL")t="SHADOW_FAIL";else if(candidateStage==="SHADOW_PARK")t="SHADOW_PARK";else if(candidateStage==="HISTORICAL_REVIEW"&&t==="HISTORICAL_READY")t="HISTORICAL_REVIEW";rows.push({address,tier:t,historicalTier,score:score(x),candidateStage:candidateStage||null,actionable:Boolean(x?.actionable),status:x?.status||null,medianHoldHours:x?.medianHoldHours??null,replay:x?.replay||null,sampleQuality:x?.sampleQuality||null,blockers:Array.isArray(x?.blockers)?x.blockers:[],shadow:ce?.shadow||null,evidenceManifest:ce?.evidenceManifest||null});}
  const order:Record<string,number>={TRIAL_READY:9,GOD:8,SHADOW_TRIAL:7,HISTORICAL_READY:6,HISTORICAL_REVIEW:5,SHADOW:4,NEAR_PASS:3,SHADOW_PARK:1,SHADOW_FAIL:0,REJECT:-1};rows.sort((a,b)=>(order[b.tier]??-9)-(order[a.tier]??-9)||b.score-a.score);
  const currentTiers=Object.fromEntries(rows.map(r=>[r.address,r.tier]));const changes=rows.filter(r=>prior?.tiers?.[r.address]!==r.tier).map(r=>({address:r.address,from:prior?.tiers?.[r.address]||null,to:r.tier,historicalTier:r.historicalTier,score:r.score,candidateStage:r.candidateStage}));
  const odinMirrors=Array.isArray(odin?.mirrors)?odin.mirrors:[];const tracked=new Set(odinMirrors.map((x:any)=>String(x?.address||"")).filter(Boolean));const buyEnabled=new Set(odinMirrors.filter((x:any)=>x?.allowBuys!==false).map((x:any)=>String(x?.address||"")).filter(Boolean));const buysDisabled=new Set(odinMirrors.filter((x:any)=>x?.allowBuys===false).map((x:any)=>String(x?.address||"")).filter(Boolean));const activeActual=new Map((Array.isArray(actual?.byMirror)?actual.byMirror:[]).map((x:any)=>[String(x?.mirror||""),x]));
  const trialReady=rows.filter(r=>r.tier==="TRIAL_READY"),historicalLeaders=rows.filter(r=>r.historicalTier==="GOD"||r.historicalTier==="HISTORICAL_READY").sort((a,b)=>b.score-a.score);
  const out={schemaVersion:5,event:"shark_scout_replacement_ladder_complete",generatedAt,actualGovernanceSafe:Boolean(actual?.summary?.governanceSafe),candidateEngineGeneratedAt:candidate?.generatedAt||null,trackedOdinMirrors:[...tracked].sort(),liveMirrors:[...buyEnabled].sort(),buysDisabledMirrors:[...buysDisabled].sort(),tiers:{GOD:rows.filter(r=>r.historicalTier==="GOD").sort((a,b)=>b.score-a.score).slice(0,TOP),TRIAL_READY:trialReady.slice(0,TOP),SHADOW_TRIAL:rows.filter(r=>r.tier==="SHADOW_TRIAL").slice(0,TOP),HISTORICAL_READY:rows.filter(r=>r.historicalTier==="HISTORICAL_READY").sort((a,b)=>b.score-a.score).slice(0,TOP),NEAR_PASS:rows.filter(r=>r.historicalTier==="NEAR_PASS"||r.historicalTier==="SHADOW").sort((a,b)=>b.score-a.score).slice(0,TOP)},historicalLeaders:historicalLeaders.slice(0,TOP),changes,replacementCandidates:trialReady.filter(r=>!tracked.has(r.address)).slice(0,TOP).map(r=>({...r,liveActual:activeActual.get(r.address)||null})),notes:["Historical strength and prospective candidacy are orthogonal: historicalTier remains visible while tier reflects the current candidate state.","replacementCandidates means only forward-shadow-complete TRIAL_READY wallets that are not already tracked in Odin.","GOD and HISTORICAL_READY remain historical-strength research labels and never imply money-bearing readiness.","SHADOW_TRIAL candidates are monitored prospectively with zero capital until their frozen time/event requirements are satisfied.","Tracked/live mirrors may appear in SHADOW_TRIAL as calibration controls, but are excluded from replacementCandidates.","This ladder remains advisory and never adds, removes, pauses, or edits an Odin mirror."]};
  await Promise.all([atomic(OUT_PATH,out),atomic(STATE_PATH,{generatedAt,tiers:currentTiers})]);console.log(JSON.stringify(out));return out;
}
if(import.meta.url===`file://${process.argv[1]}`)buildReplacementLadder().catch(e=>{console.error(JSON.stringify({event:"shark_scout_replacement_ladder_failed",error:e instanceof Error?e.message:String(e)}));process.exitCode=1;});
